import type { CategoryId } from '../categories';
import type { CategorySubgroup } from './subgroupTypes';

export const CATEGORY_SUBGROUPS_DATA: Partial<Record<CategoryId, CategorySubgroup[]>> = {
  tecnologia: [
    {
      slug: 'celulares',
      label: 'Celulares',
      keywords: ['celular', 'smartphone', 'móvil', 'movil', 'teléfono', 'telefono', 'android'],
      excludeKeywords: ['tablet', 'ipad', 'galaxy tab', 'kindle', 'tab '],
      tags: ['celulares'],
    },
    {
      slug: 'iphone',
      label: 'iPhone',
      keywords: ['iphone', 'apple iphone', 'ios', 'iphone 15', 'iphone 16', 'iphone se'],
      tags: ['iphone', 'apple'],
    },
    {
      slug: 'samsung',
      label: 'Samsung',
      keywords: ['samsung', 'galaxy', 'galaxy s', 'galaxy a', 'galaxy z', 'samsung galaxy'],
      tags: ['samsung'],
    },
    {
      slug: 'televisiones',
      label: 'Televisiones',
      keywords: [
        'smart tv',
        'televisor',
        'televisión',
        'television',
        'roku tv',
        'android tv',
        'google tv',
        'fire tv',
        'qled',
        'oled',
        'mini led',
        'pantalla smart tv',
        'pantalla smart',
        'tv ',
        ' tv',
        'televisiones',
      ],
      excludeKeywords: ['monitor', 'monitores', 'laptop', 'notebook', 'impresora', 'caminadora', 'tablet', 'treadmill', 'cinta correr', 'eliptica', 'elíptica'],
      tags: ['televisiones', 'smart-tv'],
    },
    {
      slug: 'monitores',
      label: 'Monitores',
      keywords: [
        'monitor',
        'monitores',
        'pantalla ips',
        'pantalla fhd',
        'pantalla curva',
        '144hz',
        '165hz',
        '240hz',
        'monitor gamer',
        'monitor gaming',
      ],
      excludeKeywords: ['smart tv', 'televisor', 'television', 'roku', 'android tv', 'qled tv', 'oled tv', 'caminadora', 'treadmill', 'cinta correr'],
      tags: ['monitores'],
    },
    {
      slug: 'laptops',
      label: 'Laptops',
      keywords: ['laptop', 'macbook', 'notebook', 'computadora portátil', 'computadora portatil', 'chromebook', 'ultrabook'],
      tags: ['laptops'],
    },
    {
      slug: 'tablets',
      label: 'Tablets',
      keywords: ['ipad', 'tablet', 'galaxy tab', 'kindle fire', 'tableta', 'surface'],
      tags: ['tablets'],
    },
    {
      slug: 'audio',
      label: 'Audio',
      keywords: [
        'audífono',
        'audifono',
        'airpods',
        'bocina',
        'partybox',
        'soundbar',
        'headphone',
        'earbuds',
        'parlante',
        'altavoz',
        'jbl',
        'bose',
        'sony wh',
      ],
      tags: ['audio'],
    },
    {
      slug: 'apple',
      label: 'Apple',
      keywords: ['iphone', 'ipad', 'macbook', 'airpods', 'apple watch', 'imac', 'mac mini', 'apple'],
      tags: ['apple'],
    },
    {
      slug: 'computadoras',
      label: 'Computadoras de escritorio',
      keywords: ['pc', 'computadora de escritorio', 'desktop', 'torre', 'all in one', 'imac', 'gaming pc'],
      tags: ['computadoras'],
    },
    {
      slug: 'smartwatch',
      label: 'Smartwatch',
      keywords: ['smartwatch', 'reloj inteligente', 'apple watch', 'galaxy watch', 'fitbit', 'garmin'],
      tags: ['smartwatch'],
    },
    {
      slug: 'camaras',
      label: 'Cámaras',
      keywords: ['cámara', 'camara', 'gopro', 'canon', 'nikon', 'sony alpha', 'mirrorless', 'action cam'],
      tags: ['camaras'],
    },
    {
      slug: 'almacenamiento',
      label: 'Almacenamiento',
      keywords: ['ssd', 'disco duro', 'memoria usb', 'micro sd', 'nas', 'almacenamiento externo', 'pendrive'],
      tags: ['almacenamiento'],
    },
    {
      slug: 'redes-wifi',
      label: 'Redes y WiFi',
      keywords: ['router', 'modem', 'mesh', 'wifi', 'repetidor', 'switch', 'red inalámbrica', 'red inalambrica'],
      tags: ['redes-wifi'],
    },
    {
      slug: 'accesorios-tecnologia',
      label: 'Accesorios',
      keywords: ['cargador', 'power bank', 'funda', 'case', 'cable usb', 'adaptador', 'soporte celular', 'protector pantalla'],
      tags: ['accesorios-tecnologia'],
    },
    {
      slug: 'impresoras',
      label: 'Impresoras',
      keywords: ['impresora', 'multifuncional', 'multifunción', 'multifuncion', 'cartucho', 'tinta continua', 'pixma', 'epson', 'hp smart tank'],
      excludeKeywords: ['papel fotografico', 'papel fotográfico', 'papel termico', 'papel térmico'],
      tags: ['impresoras'],
    },
    {
      slug: 'drones',
      label: 'Drones',
      keywords: ['drone', 'dron', 'dji', 'cuadricóptero', 'cuadricoptero', 'fpv'],
      tags: ['drones'],
    },
  ],

  gaming: [
    {
      slug: 'playstation',
      label: 'PlayStation',
      keywords: ['playstation', 'ps5', 'ps4', 'ps plus', 'dualsense', 'sony ps'],
      tags: ['playstation', 'consolas'],
    },
    {
      slug: 'xbox',
      label: 'Xbox',
      keywords: ['xbox', 'xbox series', 'game pass', 'xbox one', 'microsoft xbox'],
      tags: ['xbox', 'consolas'],
    },
    {
      slug: 'nintendo',
      label: 'Nintendo',
      keywords: ['nintendo switch', 'nintendo', 'switch oled', 'joy-con', 'mario', 'zelda'],
      tags: ['nintendo', 'consolas'],
    },
    {
      slug: 'consolas',
      label: 'Consolas',
      keywords: ['consola', 'playstation', 'xbox', 'nintendo switch', 'videojuegos consola'],
      tags: ['consolas'],
    },
    {
      slug: 'videojuegos',
      label: 'Videojuegos',
      keywords: ['videojuego', 'juego ps5', 'juego xbox', 'juego switch', 'game pass', 'edición', 'edicion'],
      tags: ['videojuegos'],
    },
    {
      slug: 'pc-gaming',
      label: 'PC Gaming',
      keywords: ['pc gaming', 'tarjeta gráfica', 'tarjeta grafica', 'gpu', 'rtx', 'radeon', 'steam'],
      tags: ['pc-gaming'],
    },
    {
      slug: 'accesorios-gaming',
      label: 'Accesorios gaming',
      keywords: ['control ps5', 'control xbox', 'headset gaming', 'auricular gamer', 'teclado mecánico', 'mouse gamer'],
      tags: ['accesorios-gaming'],
    },
    {
      slug: 'sillas-gamer',
      label: 'Sillas gamer',
      keywords: ['silla gamer', 'silla gaming', 'asiento gamer', 'ergonómica gamer'],
      tags: ['sillas-gamer'],
    },
    {
      slug: 'monitores-gaming',
      label: 'Monitores gaming',
      keywords: ['monitor gaming', '144hz', '240hz', 'monitor gamer', 'pantalla gaming'],
      tags: ['monitores-gaming'],
    },
    {
      slug: 'realidad-virtual',
      label: 'Realidad virtual',
      keywords: ['realidad virtual', 'vr', 'meta quest', 'oculus', 'psvr', 'visores vr'],
      tags: ['realidad-virtual'],
    },
  ],

  supermercado: [
    {
      slug: 'despensa',
      label: 'Despensa',
      keywords: ['arroz', 'pasta', 'aceite', 'atún', 'atun', 'cereal', 'despensa', 'frijol', 'harina', 'salsa'],
      tags: ['despensa'],
    },
    {
      slug: 'bebidas',
      label: 'Bebidas',
      keywords: ['cerveza', 'vino', 'refresco', 'café', 'cafe', 'bebida', 'agua', 'jugo', 'energética', 'energetica'],
      tags: ['bebidas'],
    },
    {
      slug: 'snacks',
      label: 'Snacks',
      keywords: ['snack', 'galleta', 'chocolate', 'dulce', 'botana', 'papas fritas', 'palomitas', 'churros'],
      tags: ['snacks'],
    },
    {
      slug: 'lacteos',
      label: 'Lácteos',
      keywords: ['leche', 'yogurt', 'queso', 'mantequilla', 'crema', 'lácteo', 'lacteo'],
      tags: ['lacteos'],
    },
    {
      slug: 'carnes',
      label: 'Carnes y proteínas',
      keywords: ['carne', 'pollo', 'res', 'cerdo', 'pescado', 'jamón', 'jamon', 'salchicha', 'proteína', 'proteina'],
      tags: ['carnes'],
    },
    {
      slug: 'frutas-verduras',
      label: 'Frutas y verduras',
      keywords: ['fruta', 'verdura', 'manzana', 'plátano', 'platano', 'tomate', 'lechuga', 'fresco'],
      tags: ['frutas-verduras'],
    },
    {
      slug: 'congelados',
      label: 'Congelados',
      keywords: ['congelado', 'helado', 'nuggets', 'pizza congelada', 'vegetales congelados', 'freezer'],
      tags: ['congelados'],
    },
    {
      slug: 'panaderia',
      label: 'Panadería',
      keywords: ['pan', 'pan dulce', 'bolillo', 'tortilla', 'panadería', 'panaderia', 'pastel', 'repostería'],
      tags: ['panaderia'],
    },
    {
      slug: 'limpieza-hogar',
      label: 'Limpieza del hogar',
      keywords: ['detergente', 'cloro', 'limpiador', 'papel higiénico', 'papel higienico', 'jabón de trastes', 'jabon de trastes'],
      tags: ['limpieza-hogar'],
    },
    {
      slug: 'mascotas-alimento',
      label: 'Alimento para mascotas',
      keywords: ['perro', 'gato', 'croquetas', 'alimento mascota', 'pet food', 'arena gato'],
      tags: ['mascotas-alimento'],
    },
    {
      slug: 'organicos',
      label: 'Orgánicos y saludables',
      keywords: ['orgánico', 'organico', 'natural', 'sin gluten', 'vegano', 'saludable', 'integral'],
      tags: ['organicos'],
    },
    {
      slug: 'bebidas-alcoholicas',
      label: 'Bebidas alcohólicas',
      keywords: ['cerveza', 'vino', 'tequila', 'whisky', 'ron', 'vodka', 'licor', 'destilado'],
      tags: ['bebidas-alcoholicas'],
    },
  ],

  moda: [
    {
      slug: 'tenis',
      label: 'Tenis',
      keywords: ['tenis', 'sneaker', 'zapatilla', 'nike', 'adidas', 'new balance', 'puma', 'converse', 'vans'],
      tags: ['tenis'],
    },
    {
      slug: 'ropa-hombre',
      label: 'Ropa de hombre',
      keywords: ['playera hombre', 'camisa hombre', 'pantalón hombre', 'pantalon hombre', 'traje hombre', 'sudadera hombre'],
      tags: ['ropa-hombre'],
    },
    {
      slug: 'ropa-mujer',
      label: 'Ropa de mujer',
      keywords: ['vestido', 'blusa', 'falda', 'pantalón mujer', 'pantalon mujer', 'ropa mujer', 'leggings'],
      tags: ['ropa-mujer'],
    },
    {
      slug: 'ropa-infantil',
      label: 'Ropa infantil',
      keywords: ['ropa niño', 'ropa niña', 'ropa bebé', 'ropa bebe', 'infantil', 'kids'],
      tags: ['ropa-infantil'],
    },
    {
      slug: 'accesorios-moda',
      label: 'Accesorios',
      keywords: ['bolsa', 'mochila', 'cinturón', 'cinturon', 'bufanda', 'gorra', 'cartera'],
      tags: ['accesorios-moda'],
    },
    {
      slug: 'relojes',
      label: 'Relojes',
      keywords: ['reloj', 'casio', 'citizen', 'fossil', 'reloj pulsera', 'cronógrafo', 'cronografo'],
      tags: ['relojes'],
    },
    {
      slug: 'bolsas',
      label: 'Bolsas y mochilas',
      keywords: ['bolsa', 'mochila', 'maletín', 'maletin', 'crossbody', 'tote', 'backpack'],
      tags: ['bolsas'],
    },
    {
      slug: 'ropa-deportiva',
      label: 'Ropa deportiva',
      keywords: ['ropa deportiva', 'leggings', 'short deportivo', 'sudadera deportiva', 'top deportivo', 'activewear'],
      tags: ['ropa-deportiva'],
    },
    {
      slug: 'lentes',
      label: 'Lentes',
      keywords: ['lentes de sol', 'gafas', 'ray-ban', 'oakley', 'anteojos', 'lentes graduados'],
      tags: ['lentes'],
    },
    {
      slug: 'joyeria',
      label: 'Joyería',
      keywords: ['anillo', 'collar', 'aretes', 'pulsera', 'joyería', 'joyeria', 'plata', 'oro'],
      tags: ['joyeria'],
    },
    {
      slug: 'ropa-interior',
      label: 'Ropa interior',
      keywords: ['calzon', 'calzón', 'boxer', 'brasier', 'sostén', 'sosten', 'ropa interior', 'pijama'],
      tags: ['ropa-interior'],
    },
    {
      slug: 'calzado',
      label: 'Calzado',
      keywords: ['zapatos', 'sandalias', 'botas', 'huaraches', 'mocasines', 'calzado formal'],
      tags: ['calzado'],
    },
  ],

  belleza: [
    {
      slug: 'perfumes',
      label: 'Perfumes',
      keywords: ['perfume', 'fragancia', 'eau de toilette', 'colonia', 'aroma', 'edp', 'edt'],
      tags: ['perfumes'],
    },
    {
      slug: 'skincare',
      label: 'Cuidado de la piel',
      keywords: ['serum', 'crema facial', 'skincare', 'protector solar', 'hidratante', 'limpiador facial', 'tónico'],
      tags: ['skincare'],
    },
    {
      slug: 'maquillaje',
      label: 'Maquillaje',
      keywords: ['maquillaje', 'labial', 'rubor', 'base líquida', 'base liquida', 'rimel', 'sombra', 'delineador'],
      tags: ['maquillaje'],
    },
    {
      slug: 'cabello',
      label: 'Cuidado del cabello',
      keywords: ['shampoo', 'champú', 'champu', 'acondicionador', 'tinte', 'secadora', 'plancha cabello', 'tratamiento capilar'],
      tags: ['cabello'],
    },
    {
      slug: 'cuidado-personal',
      label: 'Cuidado personal',
      keywords: ['desodorante', 'jabón', 'jabon', 'gel de baño', 'afeitadora', 'rasuradora', 'crema corporal'],
      tags: ['cuidado-personal'],
    },
    {
      slug: 'unas',
      label: 'Uñas',
      keywords: ['uñas', 'unas', 'esmalte', 'manicure', 'gelish', 'acrilico', 'acrílico', 'nail art'],
      tags: ['unas'],
    },
    {
      slug: 'barberia',
      label: 'Barbería',
      keywords: ['barbería', 'barberia', 'afeitadora', 'máquina de cortar', 'maquina de cortar', 'navaja', 'barba'],
      tags: ['barberia'],
    },
    {
      slug: 'solares',
      label: 'Protectores solares',
      keywords: ['protector solar', 'bloqueador', 'fps 50', 'fps 30', 'sunscreen', 'after sun'],
      tags: ['solares'],
    },
    {
      slug: 'dermocosmetica',
      label: 'Dermocosmética',
      keywords: ['dermocosmética', 'dermocosmetica', 'la roche', 'eucerin', 'cerave', 'vichy', 'dermatológico'],
      tags: ['dermocosmetica'],
    },
  ],

  bebes: [
    {
      slug: 'panales',
      label: 'Pañales',
      keywords: ['pañal', 'panal', 'pañales', 'panales', 'huggies', 'pampers', 'toallitas húmedas', 'toallitas humedas'],
      tags: ['panales'],
    },
    {
      slug: 'formula',
      label: 'Fórmula y alimentación',
      keywords: ['fórmula', 'formula', 'leche en polvo', 'nan', 'enfamil', 'similac', 'papilla', 'cereal bebé'],
      tags: ['formula'],
    },
    {
      slug: 'ropa-bebe',
      label: 'Ropa de bebé',
      keywords: ['ropa bebé', 'ropa bebe', 'mameluco', 'body bebé', 'pijama bebé', 'conjunto bebé'],
      tags: ['ropa-bebe'],
    },
    {
      slug: 'carriolas',
      label: 'Carriolas y portabebés',
      keywords: ['carriola', 'cochecito', 'portabebé', 'portabebe', 'silla de paseo', 'travel system'],
      tags: ['carriolas'],
    },
    {
      slug: 'juguetes-bebe',
      label: 'Juguetes de bebé',
      keywords: ['juguete bebé', 'juguete bebe', 'mordedor', 'gimnasio bebé', 'sonajero', 'peluche bebé'],
      tags: ['juguetes-bebe'],
    },
    {
      slug: 'lactancia',
      label: 'Lactancia',
      keywords: ['extractor', 'biberón', 'biberon', 'chupón', 'chupon', 'almohada lactancia', 'taza antiderrame'],
      tags: ['lactancia'],
    },
    {
      slug: 'cunas',
      label: 'Cunas y descanso',
      keywords: ['cuna', 'moisés', 'moises', 'colchón bebé', 'colchon bebe', 'cuna colecho', 'bassinet'],
      tags: ['cunas'],
    },
    {
      slug: 'seguridad-bebe',
      label: 'Seguridad',
      keywords: ['silla de auto', 'autoasiento', 'monitor bebé', 'monitor bebe', 'barandal', 'protector enchufe'],
      tags: ['seguridad-bebe'],
    },
    {
      slug: 'bano-bebe',
      label: 'Baño de bebé',
      keywords: ['bañera bebé', 'banera bebe', 'shampoo bebé', 'toalla bebé', 'termómetro bebé', 'termometro bebe'],
      tags: ['bano-bebe'],
    },
  ],

  hogar: [
    {
      slug: 'electrodomesticos',
      label: 'Electrodomésticos',
      keywords: ['refrigerador', 'lavadora', 'secadora', 'microondas', 'licuadora', 'freidora', 'horno', 'estufa'],
      tags: ['electrodomesticos'],
    },
    {
      slug: 'cocina',
      label: 'Cocina',
      keywords: ['sartén', 'sarten', 'olla', 'cafetera', 'horno', 'air fryer', 'ollas', 'cuchillos', 'vajilla'],
      tags: ['cocina'],
    },
    {
      slug: 'limpieza',
      label: 'Limpieza',
      keywords: ['detergente', 'cloro', 'limpieza', 'papel higiénico', 'papel higienico', 'aspiradora', 'trapeador', 'escoba'],
      tags: ['limpieza'],
    },
    {
      slug: 'muebles',
      label: 'Muebles',
      keywords: ['silla', 'mesa', 'escritorio', 'colchón', 'colchon', 'shelf', 'estante', 'sofá', 'sofa', 'buró'],
      excludeKeywords: ['silla gamer', 'silla gaming', 'gamer', 'parrilla', 'asador', 'barbacoa'],
      tags: ['muebles'],
    },
    {
      slug: 'colchones',
      label: 'Colchones',
      keywords: ['colchón', 'colchon', 'base cama', 'almohada', 'memory foam', 'spring air', 'simmons'],
      tags: ['colchones'],
    },
    {
      slug: 'decoracion',
      label: 'Decoración',
      keywords: ['cuadro', 'cojín', 'cojin', 'cortina', 'alfombra', 'decoración', 'decoracion', 'lámpara decorativa'],
      tags: ['decoracion'],
    },
    {
      slug: 'iluminacion',
      label: 'Iluminación',
      keywords: ['lámpara', 'lampara', 'foco led', 'bombilla', 'luz led', 'luminaria', 'plafón', 'plafon'],
      tags: ['iluminacion'],
    },
    {
      slug: 'banos',
      label: 'Baños',
      keywords: ['toalla', 'regadera', 'llave mezcladora', 'inodoro', 'lavabo', 'accesorios baño', 'tapete baño'],
      tags: ['banos'],
    },
    {
      slug: 'organizacion',
      label: 'Organización',
      keywords: ['organizador', 'caja almacenamiento', 'closet', 'repisa', 'canasto', 'gavetero', 'estante'],
      tags: ['organizacion'],
    },
    {
      slug: 'climatizacion',
      label: 'Climatización',
      keywords: ['aire acondicionado', 'minisplit', 'ventilador', 'calefactor', 'purificador aire', 'deshumidificador'],
      tags: ['climatizacion'],
    },
    {
      slug: 'blancos',
      label: 'Blancos',
      keywords: ['sábana', 'sabana', 'edredón', 'edredon', 'funda', 'cobija', 'toalla', 'blancos'],
      tags: ['blancos'],
    },
    {
      slug: 'herramientas-hogar',
      label: 'Herramientas del hogar',
      keywords: ['taladro', 'martillo', 'destornillador', 'caja herramientas', 'escalera', 'multímetro', 'multimetro'],
      tags: ['herramientas-hogar'],
    },
  ],

  jardin: [
    {
      slug: 'plantas',
      label: 'Plantas',
      keywords: ['planta', 'maceta', 'semilla', 'fertilizante', 'tierra', 'jardín', 'jardin', 'suculenta'],
      tags: ['plantas'],
    },
    {
      slug: 'herramientas-jardin',
      label: 'Herramientas de jardín',
      keywords: [
        'podadora',
        'manguera',
        'aspersor',
        'pala jardín',
        'rastrillo',
        'tijera podar',
        'motosierra',
        'desbrozador',
        'desmalezadora',
        'compresor',
        'sierra circular',
        'taladro inalambrico',
        'taladro inalámbrico',
      ],
      tags: ['herramientas-jardin'],
    },
    {
      slug: 'muebles-exterior',
      label: 'Muebles de exterior',
      keywords: ['silla exterior', 'mesa jardín', 'sillón exterior', 'hamaca', 'sombrilla', 'muebles patio'],
      tags: ['muebles-exterior'],
    },
    {
      slug: 'parrillas',
      label: 'Parrillas',
      keywords: ['parrilla', 'asador', 'carbón', 'carbon', 'bbq', 'barbacoa', 'grill', 'accesorios parrilla'],
      tags: ['parrillas'],
    },
    {
      slug: 'riego',
      label: 'Riego',
      keywords: ['manguera', 'aspersor', 'sistema riego', 'goteo', 'regadera', 'conector manguera', 'timer riego'],
      tags: ['riego'],
    },
    {
      slug: 'macetas',
      label: 'Macetas y contenedores',
      keywords: ['maceta', 'jardín vertical', 'jardin vertical', 'contenedor plantas', 'macetero', 'plato maceta'],
      tags: ['macetas'],
    },
    {
      slug: 'cesped',
      label: 'Césped',
      keywords: ['césped', 'cesped', 'pasto', 'podadora césped', 'podadora cesped', 'fertilizante césped', 'semilla pasto'],
      tags: ['cesped'],
    },
    {
      slug: 'iluminacion-exterior',
      label: 'Iluminación exterior',
      keywords: ['luz jardín', 'luz jardin', 'farol', 'reflectores', 'luz solar exterior', 'guirnalda exterior'],
      tags: ['iluminacion-exterior'],
    },
    {
      slug: 'control-plagas',
      label: 'Control de plagas',
      keywords: ['insecticida', 'plaguicida', 'repelente', 'trampa insectos', 'fungicida', 'control plagas'],
      tags: ['control-plagas'],
    },
  ],

  autos: [
    {
      slug: 'llantas',
      label: 'Llantas',
      keywords: ['llanta', 'neumático', 'neumatico', 'rin', 'michelin', 'goodyear', 'pirelli', 'hankook'],
      tags: ['llantas'],
    },
    {
      slug: 'aceites',
      label: 'Aceites y lubricantes',
      keywords: ['aceite motor', 'lubricante', 'anticongelante', 'aceite transmisión', 'aceite transmision', 'aditivo motor'],
      tags: ['aceites'],
    },
    {
      slug: 'baterias',
      label: 'Baterías',
      keywords: ['batería auto', 'bateria auto', 'batería carro', 'bateria carro', 'acumulador', 'cargador batería'],
      tags: ['baterias'],
    },
    {
      slug: 'accesorios-auto',
      label: 'Accesorios',
      keywords: ['portaequipaje', 'funda asiento', 'organizador auto', 'cargador auto', 'soporte celular auto', 'tapete auto'],
      tags: ['accesorios-auto'],
    },
    {
      slug: 'audio-auto',
      label: 'Audio para auto',
      keywords: ['estéreo auto', 'estereo auto', 'bocina auto', 'subwoofer', 'android auto', 'carplay'],
      tags: ['audio-auto'],
    },
    {
      slug: 'limpieza-auto',
      label: 'Limpieza y cuidado',
      keywords: ['shampoo auto', 'cera auto', 'aspiradora auto', 'ambientador auto', 'pulidor', 'toalla microfibra auto'],
      tags: ['limpieza-auto'],
    },
    {
      slug: 'motos',
      label: 'Motos',
      keywords: ['motocicleta', 'moto', 'casco moto', 'guantes moto', 'chaleco moto', 'accesorios moto'],
      tags: ['motos'],
    },
    {
      slug: 'refacciones',
      label: 'Refacciones',
      keywords: ['refacción', 'refaccion', 'filtro aceite', 'pastillas freno', 'bujía', 'bujia', 'amortiguador', 'alternador'],
      tags: ['refacciones'],
    },
    {
      slug: 'seguridad-auto',
      label: 'Seguridad vial',
      keywords: ['gato hidráulico', 'gato hidraulico', 'cables paso corriente', 'triángulo', 'triangulo', 'extintor auto', 'dashcam'],
      tags: ['seguridad-auto'],
    },
  ],

  entretenimiento: [
    {
      slug: 'libros',
      label: 'Libros',
      keywords: ['libro', 'novela', 'ebook', 'kindle', 'literatura', 'comic', 'cómic', 'manga'],
      tags: ['libros'],
    },
    {
      slug: 'musica',
      label: 'Música',
      keywords: ['cd', 'vinilo', 'disco', 'música', 'musica', 'partitura', 'tocadiscos'],
      tags: ['musica'],
    },
    {
      slug: 'peliculas',
      label: 'Películas y series',
      keywords: ['película', 'pelicula', 'blu-ray', 'bluray', 'dvd', 'serie', 'colección películas', 'coleccion peliculas'],
      tags: ['peliculas'],
    },
    {
      slug: 'instrumentos',
      label: 'Instrumentos musicales',
      keywords: ['guitarra', 'piano', 'batería', 'bateria', 'ukulele', 'teclado musical', 'violín', 'violin'],
      tags: ['instrumentos'],
    },
    {
      slug: 'coleccionables',
      label: 'Coleccionables',
      keywords: ['figura coleccionable', 'funko', 'lego', 'hot wheels', 'tarjeta coleccionable', 'memorabilia'],
      tags: ['coleccionables'],
    },
    {
      slug: 'juegos-mesa',
      label: 'Juegos de mesa',
      keywords: ['juego de mesa', 'catan', 'monopoly', 'cartas', 'rompecabezas', 'board game', 'ajedrez'],
      tags: ['juegos-mesa'],
    },
    {
      slug: 'tickets-eventos',
      label: 'Boletos y eventos',
      keywords: ['boleto', 'concierto', 'festival', 'teatro', 'evento', 'ticketmaster', 'entrada'],
      tags: ['tickets-eventos'],
    },
    {
      slug: 'streaming',
      label: 'Streaming',
      keywords: ['netflix', 'disney plus', 'prime video', 'spotify', 'hbo', 'streaming', 'apple tv'],
      tags: ['streaming'],
    },
    {
      slug: 'fotografia',
      label: 'Fotografía',
      keywords: ['cámara', 'camara', 'lente fotográfico', 'lente fotografico', 'tripie', 'trípode', 'flash', 'filtro cámara'],
      tags: ['fotografia'],
    },
  ],

  deportes: [
    {
      slug: 'fitness',
      label: 'Fitness',
      keywords: [
        'gym',
        'mancuerna',
        'pesa',
        'banco gym',
        'cinta correr',
        'caminadora',
        'treadmill',
        'bicicleta estática',
        'bicicleta estatica',
        'elíptica',
        'eliptica',
        'fitness',
        'creatina',
        'pre workout',
        'proteína',
        'proteina',
      ],
      excludeKeywords: ['bicicleta montaña', 'bicicleta carretera', 'casco bici'],
      tags: ['fitness'],
    },
    {
      slug: 'running',
      label: 'Running',
      keywords: ['running', 'correr', 'tenis running', 'sudadera running', 'mallas', 'reloj running', 'maratón', 'maraton'],
      tags: ['running'],
    },
    {
      slug: 'ciclismo',
      label: 'Ciclismo',
      keywords: ['bicicleta', 'ciclismo', 'casco bici', 'luces bici', 'cadena bici', 'llanta bici', 'ciclista'],
      tags: ['ciclismo'],
    },
    {
      slug: 'futbol',
      label: 'Fútbol',
      keywords: ['fútbol', 'futbol', 'balón', 'balon', 'jersey', 'guantes portero', 'cancha', 'liga mx'],
      tags: ['futbol'],
    },
    {
      slug: 'natacion',
      label: 'Natación',
      keywords: ['natación', 'natacion', 'traje baño', 'goggles', 'aletas', 'gorro natación', 'alberca'],
      tags: ['natacion'],
    },
    {
      slug: 'camping',
      label: 'Camping',
      keywords: ['camping', 'carpa', 'sleeping bag', 'saco dormir', 'linterna', 'mochila camping', 'hielera'],
      tags: ['camping'],
    },
    {
      slug: 'deportes-acuaticos',
      label: 'Deportes acuáticos',
      keywords: ['surf', 'paddle', 'snorkel', 'kayak', 'wetsuit', 'tabla surf', 'deportes acuáticos', 'deportes acuaticos'],
      tags: ['deportes-acuaticos'],
    },
    {
      slug: 'yoga',
      label: 'Yoga y pilates',
      keywords: ['yoga', 'pilates', 'mat yoga', 'bloque yoga', 'lululemon', 'ropa yoga', 'meditación', 'meditacion'],
      tags: ['yoga'],
    },
    {
      slug: 'outdoor',
      label: 'Outdoor',
      keywords: ['senderismo', 'trekking', 'bastón', 'baston', 'botas hiking', 'chaleco outdoor', 'montañismo', 'montanismo'],
      tags: ['outdoor'],
    },
  ],

  viajes: [
    {
      slug: 'vuelos',
      label: 'Vuelos',
      keywords: ['vuelo', 'boletos de avión', 'boletos de avion', 'volaris', 'aeromexico', 'aeroméxico', 'viva aerobus', 'interjet'],
      tags: ['vuelos'],
    },
    {
      slug: 'hoteles',
      label: 'Hoteles',
      keywords: ['hotel', 'hospedaje', 'airbnb', 'booking', 'resort', 'hostal', 'alojamiento'],
      tags: ['hoteles'],
    },
    {
      slug: 'maletas',
      label: 'Maletas',
      keywords: ['maleta', 'equipaje', 'carry on', 'mochila viaje', 'set maletas', 'trolley', 'maletín viaje'],
      tags: ['maletas'],
    },
    {
      slug: 'renta-autos',
      label: 'Renta de autos',
      keywords: ['renta auto', 'renta de auto', 'alquiler auto', 'hertz', 'avis', 'enterprise', 'car rental'],
      tags: ['renta-autos'],
    },
    {
      slug: 'paquetes',
      label: 'Paquetes turísticos',
      keywords: ['paquete turístico', 'paquete turistico', 'todo incluido', 'vacaciones', 'viaje todo incluido', 'tour'],
      tags: ['paquetes'],
    },
    {
      slug: 'cruceros',
      label: 'Cruceros',
      keywords: ['crucero', 'cruise', 'royal caribbean', 'carnival', 'norwegian', 'barco crucero'],
      tags: ['cruceros'],
    },
    {
      slug: 'seguros-viaje',
      label: 'Seguros de viaje',
      keywords: ['seguro viaje', 'seguro de viaje', 'asistencia viaje', 'cobertura médica viaje', 'travel insurance'],
      tags: ['seguros-viaje'],
    },
    {
      slug: 'actividades',
      label: 'Actividades y tours',
      keywords: ['tour', 'excursión', 'excursion', 'parque temático', 'disney', 'universal', 'actividad turística'],
      tags: ['actividades'],
    },
    {
      slug: 'transporte-local',
      label: 'Transporte local',
      keywords: ['uber', 'taxi', 'metro', 'autobús turístico', 'autobus turistico', 'transporte aeropuerto', 'shuttle'],
      tags: ['transporte-local'],
    },
  ],

  servicios: [
    {
      slug: 'streaming',
      label: 'Streaming',
      keywords: ['netflix', 'disney plus', 'prime video', 'spotify', 'hbo', 'streaming', 'apple tv', 'youtube premium'],
      tags: ['streaming'],
    },
    {
      slug: 'comida-domicilio',
      label: 'Comida a domicilio',
      keywords: ['uber eats', 'rappi', 'didi food', 'dominos', "domino's", 'delivery', 'comida a domicilio'],
      tags: ['comida-domicilio'],
    },
    {
      slug: 'bancos',
      label: 'Bancos y tarjetas',
      keywords: ['banco', 'tarjeta de crédito', 'tarjeta de credito', 'msi', 'meses sin intereses', 'bbva', 'banorte', 'santander'],
      tags: ['bancos'],
    },
    {
      slug: 'telefonia',
      label: 'Telefonía e internet',
      keywords: ['telcel', 'at&t', 'movistar', 'plan celular', 'internet hogar', 'fibra óptica', 'fibra optica', 'recarga'],
      tags: ['telefonia'],
    },
    {
      slug: 'membresias',
      label: 'Membresías',
      keywords: ['membresía', 'membresia', 'costco', 'sams', "sam's", 'amazon prime', 'club precios', 'suscripción', 'suscripcion'],
      tags: ['membresias'],
    },
    {
      slug: 'seguros',
      label: 'Seguros',
      keywords: ['seguro', 'seguro auto', 'seguro gastos médicos', 'seguro gastos medicos', 'seguro vida', 'gnp', 'axa'],
      tags: ['seguros'],
    },
    {
      slug: 'educacion-online',
      label: 'Educación en línea',
      keywords: ['curso en línea', 'curso en linea', 'udemy', 'coursera', 'platzi', 'domestika', 'certificación', 'certificacion'],
      tags: ['educacion-online'],
    },
    {
      slug: 'software',
      label: 'Software y apps',
      keywords: ['microsoft 365', 'office', 'adobe', 'antivirus', 'licencia software', 'vpn', 'dominio', 'hosting'],
      tags: ['software'],
    },
    {
      slug: 'gimnasios',
      label: 'Gimnasios',
      keywords: ['gimnasio', 'smart fit', 'sports world', 'membresía gym', 'membresia gym', 'clase fitness'],
      tags: ['gimnasios'],
    },
  ],
};
