/**
 * Retailer / source coverage map for Hunter — documentation as code.
 * ACTIVE | DEGRADED | DISABLED | NOT_IMPLEMENTED
 */

export type HunterSourceCoverageStatus =
  | 'ACTIVE'
  | 'DEGRADED'
  | 'DISABLED'
  | 'NOT_IMPLEMENTED';

export type HunterSourceCoverageRow = {
  retailer: string;
  ingestSourceId: string | null;
  status: HunterSourceCoverageStatus;
  discoveryMethod: string;
  affiliateSupport: 'yes' | 'partial' | 'no' | 'unknown';
  couponSupport: 'yes' | 'partial' | 'no' | 'unknown';
  priceHistorySupport: 'yes' | 'partial' | 'no' | 'unknown';
  pathToEnable: string;
  knownLimitations: string;
  /** Dominio(s) canónicos cuando aplica (autofill / reconocimiento). */
  hosts?: readonly string[];
};

export const HUNTER_SOURCE_COVERAGE: HunterSourceCoverageRow[] = [
  {
    retailer: 'Mercado Libre México',
    ingestSourceId: 'ml_worker',
    status: 'ACTIVE',
    discoveryMethod: 'Playwright GHA → externalWorker',
    affiliateSupport: 'yes',
    couponSupport: 'partial',
    priceHistorySupport: 'partial',
    pathToEnable: 'BOT_INGEST_EXTERNAL_WORKER + GHA workflow',
    knownLimitations: 'HTML antibot; shortlinks meli.la; catalog image fail-closed',
    hosts: ['mercadolibre.com.mx', 'meli.la'],
  },
  {
    retailer: 'Mercado Libre API legacy',
    ingestSourceId: 'ml_api',
    status: 'DEGRADED',
    discoveryMethod: 'Official search/highlights API',
    affiliateSupport: 'yes',
    couponSupport: 'no',
    priceHistorySupport: 'partial',
    pathToEnable: 'BOT_INGEST_DISCOVER_ML',
    knownLimitations: 'Rate limits; OAuth optional',
    hosts: ['mercadolibre.com.mx'],
  },
  {
    retailer: 'Amazon México',
    ingestSourceId: 'amazon_asin',
    status: 'DEGRADED',
    discoveryMethod: 'ASIN list + HTML/PA-API',
    affiliateSupport: 'yes',
    couponSupport: 'partial',
    priceHistorySupport: 'yes',
    pathToEnable: 'BOT_INGEST amazon ASINs / PA-API keys',
    knownLimitations: 'HTML captcha; PA-API credentials required for reliable meta',
    hosts: ['amazon.com.mx', 'amzn.to', 'a.co'],
  },
  {
    retailer: 'Walmart México',
    ingestSourceId: 'walmart_mx',
    status: 'DISABLED',
    discoveryMethod: 'Day-to-Day sitemap/promo adapters',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'DAY_TO_DAY_WALMART_ENABLED + DISCOVERY',
    knownLimitations: 'Marked DEGRADED in day-to-day; legal/ToS review before scrape scale',
    hosts: ['walmart.com.mx', 'walmart.page.link'],
  },
  {
    retailer: 'Bodega Aurrera',
    ingestSourceId: 'bodega_aurrera_mx',
    status: 'DISABLED',
    discoveryMethod: 'Day-to-Day adapters',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'DAY_TO_DAY_BODEGA_ENABLED',
    knownLimitations: 'DEGRADED surface',
    hosts: ['bodegaaurrera.com.mx'],
  },
  {
    retailer: 'Chedraui',
    ingestSourceId: 'chedraui_mx',
    status: 'DISABLED',
    discoveryMethod: 'Day-to-Day adapters (READY surface)',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'DAY_TO_DAY_CHEDRAUI_ENABLED',
    knownLimitations: 'Flag default OFF',
    hosts: ['chedraui.com.mx'],
  },
  {
    retailer: 'AliExpress',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'partial',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate network feed; autofill vía parseGeneric',
    knownLimitations: 'Autofill allowlisted; no Hunter adapter',
    hosts: ['aliexpress.com'],
  },
  {
    retailer: 'Temu',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'partial',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate network feed; autofill vía parseGeneric',
    knownLimitations: 'Autofill allowlisted; no Hunter adapter',
    hosts: ['temu.com', 'temu.to'],
  },
  {
    retailer: 'SHEIN',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'partial',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate network feed; autofill vía parseGeneric',
    knownLimitations: 'Autofill allowlisted; no Hunter adapter',
    hosts: ['shein.com', 'shein.com.mx'],
  },
  {
    retailer: 'eBay',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/API antes de scrape; autofill allowlisted',
    knownLimitations: 'Autofill allowlisted; no Hunter adapter',
    hosts: ['ebay.com', 'ebay.com.mx', 'ebay.mx', 'ebay.to'],
  },
  {
    retailer: 'Shopee México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first; autofill allowlisted',
    knownLimitations: 'Autofill allowlisted; no Hunter adapter',
    hosts: ['shopee.com.mx', 'shopee.mx', 'shp.ee'],
  },
  {
    retailer: 'Liverpool',
    ingestSourceId: 'liverpool_mx',
    status: 'DEGRADED',
    discoveryMethod: 'seed_pdp',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Set BOT_INGEST_LIVERPOOL_URLS to liverpool.com.mx/tienda/pdp/... URLs',
    knownLimitations: 'Day 6 seed discovery only — no search scrape; empty env disables source',
    hosts: ['liverpool.com.mx', 'liverpool.app.link'],
  },
  {
    retailer: 'Coppel',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Autofill JSON-LD listo; Hunter: affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['coppel.com', 'coppel.com.mx', 'coppel.app.link'],
  },
  {
    retailer: 'El Palacio de Hierro',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['elpalaciodehierro.com'],
  },
  {
    retailer: 'Sears México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['sears.com.mx'],
  },
  {
    retailer: 'Suburbia',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['suburbia.com.mx'],
  },
  {
    retailer: 'Elektra',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['elektra.com.mx', 'elektra.mx'],
  },
  {
    retailer: 'Sanborns',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['sanborns.com.mx'],
  },
  {
    retailer: 'ClaroShop',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['claroshop.com', 'claroshop.com.mx'],
  },
  {
    retailer: 'Costco México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'no',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Membership / feed; evitar scrape agresivo',
    knownLimitations: 'No adapter',
    hosts: ['costco.com.mx', 'cost.co'],
  },
  {
    retailer: "Sam's Club México",
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Membership / feed; evitar scrape agresivo',
    knownLimitations: 'No adapter',
    hosts: ['sams.com.mx'],
  },
  {
    retailer: 'Office Depot México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['officedepot.com.mx'],
  },
  {
    retailer: 'OfficeMax México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['officemax.com.mx'],
  },
  {
    retailer: 'Soriana',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Policy review primero (ToS restringe spiders)',
    knownLimitations: 'retailerDiscovery BLOCKED_PENDING_POLICY_REVIEW',
    hosts: ['soriana.com'],
  },
  {
    retailer: 'City Club',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Misma precaución ToS que Soriana',
    knownLimitations: 'No adapter',
    hosts: ['cityclub.com.mx'],
  },
  {
    retailer: 'H-E-B México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['heb.com.mx'],
  },
  {
    retailer: 'La Comer',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['lacomer.com.mx'],
  },
  {
    retailer: 'City Market',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['citymarket.com.mx'],
  },
  {
    retailer: 'Fresko',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['fresko.com.mx'],
  },
  {
    retailer: 'Superama (legacy)',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Preferir walmart.com.mx (rebrand Express)',
    knownLimitations: 'Dominio legacy; autofill allowlisted',
    hosts: ['superama.com.mx', 'superama.com'],
  },
  {
    retailer: 'Home Depot México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: 'sitemap→PDP investigation (CATALOG_ONLY)',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Autofill JSON-LD listo; Hunter FASE 9.1 — no activar sin originalPrice',
    knownLimitations: 'retailerDiscovery CATALOG_ONLY; sin HunterSource',
    hosts: ['homedepot.com.mx'],
  },
  {
    retailer: 'Sodimac México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['sodimac.com.mx'],
  },
  {
    retailer: 'Cyberpuerta',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['cyberpuerta.mx', 'cyberpuerta.com', 'cyberpuerta.com.mx'],
  },
  {
    retailer: 'DDTech',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['ddtech.mx'],
  },
  {
    retailer: 'PCEL',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['pcel.com'],
  },
  {
    retailer: 'Doto',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['doto.com.mx'],
  },
  {
    retailer: 'Steren',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['steren.com.mx'],
  },
  {
    retailer: 'RadioShack México',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['radioshack.com.mx'],
  },
  {
    retailer: 'Nike',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Official affiliate / product API',
    knownLimitations: 'Autofill allowlisted; no Hunter adapter',
    hosts: ['nike.com'],
  },
  {
    retailer: 'adidas',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Official affiliate / product API',
    knownLimitations: 'Autofill allowlisted; no Hunter adapter',
    hosts: ['adidas.mx', 'adidas.com'],
  },
  {
    retailer: 'Apple',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'no',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Official store only; autofill parseGeneric',
    knownLimitations: 'Autofill allowlisted; no Hunter adapter',
    hosts: ['apple.com', 'apple.com.mx'],
  },
  {
    retailer: 'iShop Mixup',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['ishopmixup.com', 'mixup.com.mx'],
  },
  {
    retailer: 'Innova Sport',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['innovasport.com'],
  },
  {
    retailer: 'Price Shoes',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['priceshoes.com'],
  },
  {
    retailer: 'Andrea',
    ingestSourceId: null,
    status: 'NOT_IMPLEMENTED',
    discoveryMethod: '—',
    affiliateSupport: 'unknown',
    couponSupport: 'unknown',
    priceHistorySupport: 'no',
    pathToEnable: 'Affiliate/feed first',
    knownLimitations: 'No adapter',
    hosts: ['andrea.com.mx'],
  },
];
