import type { ScoreBreakdown } from '@/lib/bots/ingest/scoreIngestCandidate';
import type { HunterCandidateDecision, HunterRejectionStage } from './taxonomy';
import type { ScoreSignal } from './scoreExplanation';

export type HunterCandidateRecord = {
  runId: string;
  candidateKey: string;
  source: string;
  retailer: string | null;
  sourceUrl: string;
  canonicalUrl: string;
  title: string | null;
  description: string | null;
  imageUrl: string | null;
  seller: string | null;
  brand: string | null;
  category: string | null;
  subcategory: string | null;
  originalPrice: number | null;
  salePrice: number | null;
  discountPercentage: number | null;
  coupon: string | null;
  shippingCost: number | null;
  currency: string;
  availability: string | null;
  sellerRating: number | null;
  productRating: number | null;
  reviewCount: number | null;
  productFingerprint: string | null;
  duplicateOf: string | null;
  duplicateClusterId: string | null;
  hunterScore: number | null;
  scoreBreakdown: ScoreBreakdown | Record<string, unknown>;
  scoreExplanation: ScoreSignal[];
  dqeQualification: string | null;
  machineQualityDecision: string | null;
  reasonCodes: string[];
  decision: HunterCandidateDecision;
  reasonCode: string;
  reasonDetail: string | null;
  rejectionStage: HunterRejectionStage;
  evidence: Record<string, unknown>;
  rawMetadata: Record<string, unknown>;
  negativeMemoryLevel: string | null;
  insertedOfferId: string | null;
  affiliateStatus: string | null;
  discoveredAt: string;
  hunterVersion: string;
  normalizationVersion: string;
  scoringVersion: string;
  decisionPolicyVersion: string;
  /** Hardening fields (optional / nullable). */
  originalUrl?: string | null;
  affiliateUrl?: string | null;
  titleRaw?: string | null;
  titleNormalized?: string | null;
  imageUrlOriginal?: string | null;
  imageUrlResolved?: string | null;
  imageValidationStatus?: string | null;
  imageValidationReason?: string | null;
  productIdentifier?: string | null;
  urlDiagnosis?: Record<string, unknown>;
  validationErrors?: string[];
  diversityCut?: boolean;
  negativeMemoryMatch?: string | null;
  /** Discovery Experiment (optional / shadow). */
  experimentId?: string | null;
  experimentVariant?: string | null;
  discountClass?: string | null;
  /** Dual-label v1 for A/C comparison. */
  discountClassV1?: string | null;
  discountConfidence?: string | null;
  discountSource?: string | null;
  historicalPriceConfidence?: string | null;
  priceEvidence?: Record<string, unknown> | null;
  currentDecision?: string | null;
  hypotheticalDecision?: string | null;
  funnelStage?: string | null;
  funnelReason?: string | null;
  wouldTopkCut?: boolean;
  wouldDiversityCut?: boolean;
  persistedPreGate?: boolean;
  discoveryCountInRun?: number;
  firstPriceSale?: number | null;
  lastPriceSale?: number | null;
  priceChangeInRun?: number | null;
  rotPage?: number | null;
  rotSeedId?: string | null;
  rotCategoryId?: string | null;
  rotQuery?: string | null;
  rotBrand?: string | null;
  rotPriceBand?: string | null;
  axisBitmap?: Record<string, boolean> | null;
};

export type HunterIntelligenceRunSummary = {
  runId: string;
  startedAt: string;
  finishedAt: string;
  mode: 'observation';
  sources: string[];
  retailers: string[];
  candidateCount: number;
  normalizedCount: number;
  duplicateCount: number;
  rejectedCount: number;
  needsReviewCount: number;
  wouldInsertCount: number;
  insertedPendingCount: number;
  publishedCount: number;
  rejectionBreakdown: Record<string, number>;
  decisionBreakdown: Record<string, number>;
  scoreDistribution: Record<string, number>;
  hunterVersion: string;
  scoringVersion: string;
  decisionPolicyVersion: string;
};
