import type { AchievementDefinition } from './types';

/**
 * Catálogo oficial. Los nombres, familias y XP explícitos de la spec no se
 * reescriben. La experiencia no da XP: el nivel ya es la progresión.
 * Cazador en marcha III, Conversador, Participante, Semana perfecta,
 * Cazador disciplinado, Cazador influyente, Gran impacto y Experiencia
 * viven aquí aunque la vitrina de 24 no los ponga todos al frente.
 */
export const ACHIEVEMENT_CATALOG: readonly AchievementDefinition[] = [
  {
    code: 'first_trail',
    name: 'Primer rastro',
    description: 'Publica tu primera oferta aprobada.',
    unlockLine: 'Aventa ya reconoce tu primer hallazgo.',
    icon: '🏹',
    category: 'caceria',
    rarity: 'common',
    xpReward: 50,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 10,
    rule: { type: 'approved_offers', target: 1 },
    triggers: ['OFFER_APPROVED'],
    progressNoun: 'ofertas aprobadas',
  },
  {
    code: 'hunter_moving_1',
    name: 'Cazador en marcha I',
    description: 'Publica 5 ofertas aprobadas.',
    unlockLine: 'Ya estás cazando con ritmo.',
    icon: '🏹',
    category: 'caceria',
    rarity: 'common',
    xpReward: 50,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 20,
    rule: { type: 'approved_offers', target: 5 },
    triggers: ['OFFER_APPROVED'],
    progressNoun: 'ofertas aprobadas',
  },
  {
    code: 'hunter_moving_2',
    name: 'Cazador en marcha II',
    description: 'Publica 25 ofertas aprobadas.',
    unlockLine: 'Tu rastro ya se nota en el feed.',
    icon: '🏹',
    category: 'caceria',
    rarity: 'uncommon',
    xpReward: 100,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 30,
    rule: { type: 'approved_offers', target: 25 },
    triggers: ['OFFER_APPROVED'],
    progressNoun: 'ofertas aprobadas',
  },
  {
    code: 'hunter_moving_3',
    name: 'Cazador en marcha III',
    description: 'Publica 100 ofertas aprobadas.',
    unlockLine: 'Cien ofertas válidas. Esto ya es oficio.',
    icon: '🏹',
    category: 'caceria',
    rarity: 'rare',
    xpReward: 250,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 40,
    rule: { type: 'approved_offers', target: 100 },
    triggers: ['OFFER_APPROVED'],
    progressNoun: 'ofertas aprobadas',
  },
  {
    code: 'hunter_veteran',
    name: 'Cazador veterano',
    description: 'Publica 250 ofertas aprobadas.',
    unlockLine: 'Llevas un camino largo de ofertas válidas.',
    icon: '🏹',
    category: 'caceria',
    rarity: 'epic',
    xpReward: 500,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 50,
    rule: { type: 'approved_offers', target: 250 },
    triggers: ['OFFER_APPROVED'],
    progressNoun: 'ofertas aprobadas',
  },
  {
    code: 'good_eye',
    name: 'Buen ojo',
    description: 'Publica 5 ofertas que sean aprobadas sin necesidad de corrección.',
    unlockLine: 'Tus ofertas salen limpias a la primera.',
    icon: '🎯',
    category: 'precision',
    rarity: 'uncommon',
    xpReward: 50,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 60,
    rule: { type: 'clean_approvals', target: 5 },
    triggers: ['OFFER_APPROVED'],
    progressNoun: 'ofertas aprobadas sin corrección',
  },
  {
    code: 'precise_hunter',
    name: 'Cazador preciso',
    description: 'Alcanza una tasa de aprobación del 80% después de al menos 20 ofertas.',
    unlockLine: 'La mayoría de lo que publicas sí vale.',
    icon: '🎯',
    category: 'precision',
    rarity: 'rare',
    xpReward: 100,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 70,
    rule: { type: 'approval_rate', minOffers: 20, minRate: 0.8 },
    triggers: ['OFFER_APPROVED', 'OFFER_REJECTED'],
    progressNoun: 'ofertas evaluadas',
  },
  {
    code: 'eagle_eye',
    name: 'Ojo de águila',
    description: 'Demuestra una precisión excepcional al encontrar ofertas.',
    unlockLine: 'Tu precisión empieza a destacar.',
    icon: '🎯',
    category: 'precision',
    rarity: 'rare',
    xpReward: 250,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 80,
    rule: { type: 'approval_rate', minOffers: 50, minRate: 0.9 },
    triggers: ['OFFER_APPROVED', 'OFFER_REJECTED'],
    progressNoun: 'ofertas aprobadas',
  },
  {
    code: 'bargain_detector',
    name: 'Detector de gangas',
    description: 'Publica 10 ofertas que superen el umbral de calidad de Aventa.',
    unlockLine: 'Encontraste gangas que el sistema sí reconoce.',
    icon: '🎯',
    category: 'precision',
    rarity: 'epic',
    xpReward: 150,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 90,
    rule: { type: 'quality_offers', target: 10 },
    triggers: ['OFFER_APPROVED', 'QUALITY_THRESHOLD_REACHED'],
    progressNoun: 'ofertas sobre el umbral de calidad',
  },
  {
    code: 'first_help',
    name: 'Primera ayuda',
    description: 'Tu primera oferta recibe un voto positivo.',
    unlockLine: 'Alguien encontró útil lo que cazaste.',
    icon: '❤️',
    category: 'comunidad',
    rarity: 'common',
    xpReward: 25,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 100,
    rule: { type: 'received_votes', target: 1 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos positivos recibidos',
  },
  {
    code: 'good_contribution',
    name: 'Buena aportación',
    description: 'Acumula 25 votos positivos recibidos.',
    unlockLine: 'La comunidad ya apoyó varias veces tu cacería.',
    icon: '❤️',
    category: 'comunidad',
    rarity: 'uncommon',
    xpReward: 75,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 110,
    rule: { type: 'received_votes', target: 25 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos positivos recibidos',
  },
  {
    code: 'community_favorite',
    name: 'Favorito de la comunidad',
    description: 'Acumula 100 votos positivos recibidos.',
    unlockLine: 'Tus ofertas se volvieron un apoyo frecuente.',
    icon: '❤️',
    category: 'comunidad',
    rarity: 'rare',
    xpReward: 150,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 120,
    rule: { type: 'received_votes', target: 100 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos positivos recibidos',
  },
  {
    code: 'community_reference',
    name: 'Referencia de la comunidad',
    description: 'Acumula 500 votos positivos recibidos.',
    unlockLine: 'La gente vuelve a lo que tú encuentras.',
    icon: '❤️',
    category: 'comunidad',
    rarity: 'epic',
    xpReward: 500,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 130,
    rule: { type: 'received_votes', target: 500 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos positivos recibidos',
  },
  {
    code: 'conversationalist',
    name: 'Conversador',
    description: 'Recibe 10 comentarios útiles en tus ofertas.',
    unlockLine: 'Tus ofertas abrieron conversaciones que ayudaron.',
    icon: '💬',
    category: 'comunidad',
    rarity: 'uncommon',
    xpReward: 75,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 140,
    rule: { type: 'useful_comments', target: 10 },
    triggers: ['OFFER_RECEIVED_COMMENT'],
    progressNoun: 'comentarios útiles',
  },
  {
    code: 'participant',
    name: 'Participante',
    description: 'Participa de manera válida en 25 conversaciones.',
    unlockLine: 'Aportaste en conversaciones de verdad.',
    icon: '🤝',
    category: 'comunidad',
    rarity: 'rare',
    xpReward: 100,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 150,
    rule: { type: 'conversations', target: 25 },
    triggers: ['USER_COMMENTED'],
    progressNoun: 'conversaciones válidas',
  },
  {
    code: 'first_fire',
    name: 'Primer fuego',
    description: 'Contribuye en 3 días diferentes.',
    unlockLine: 'Volviste a aportar, y no solo a entrar.',
    icon: '🔥',
    category: 'constancia',
    rarity: 'common',
    xpReward: 25,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 160,
    rule: { type: 'distinct_days', target: 3 },
    triggers: ['STREAK_DAY_COMPLETED', 'OFFER_APPROVED', 'USER_VOTED', 'USER_COMMENTED'],
    progressNoun: 'días con contribución',
  },
  {
    code: 'constant_hunter',
    name: 'Cazador constante',
    description: 'Contribuye durante 7 días diferentes.',
    unlockLine: 'Siete días de aportación real.',
    icon: '🔥',
    category: 'constancia',
    rarity: 'uncommon',
    xpReward: 75,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 170,
    rule: { type: 'distinct_days', target: 7 },
    triggers: ['STREAK_DAY_COMPLETED', 'OFFER_APPROVED', 'USER_VOTED', 'USER_COMMENTED'],
    progressNoun: 'días con contribución',
  },
  {
    code: 'perfect_week',
    name: 'Semana perfecta',
    description: 'Contribuye durante 7 días consecutivos.',
    unlockLine: 'Una semana seguida de contribución real.',
    icon: '🔥',
    category: 'constancia',
    rarity: 'rare',
    xpReward: 100,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 180,
    rule: { type: 'consecutive_days', target: 7 },
    triggers: ['STREAK_DAY_COMPLETED'],
    progressNoun: 'días consecutivos',
  },
  {
    code: 'disciplined_hunter',
    name: 'Cazador disciplinado',
    description: 'Contribuye durante 14 días consecutivos.',
    unlockLine: 'Dos semanas sin soltar la contribución.',
    icon: '🔥',
    category: 'constancia',
    rarity: 'epic',
    xpReward: 150,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 190,
    rule: { type: 'consecutive_days', target: 14 },
    triggers: ['STREAK_DAY_COMPLETED'],
    progressNoun: 'días consecutivos',
  },
  {
    code: 'unstoppable',
    name: 'Imparable',
    description: 'Contribuye durante 30 días consecutivos.',
    unlockLine: 'Un mes seguido aportando de verdad.',
    icon: '🔥',
    category: 'constancia',
    rarity: 'epic',
    xpReward: 300,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 200,
    rule: { type: 'consecutive_days', target: 30 },
    triggers: ['STREAK_DAY_COMPLETED'],
    progressNoun: 'días consecutivos',
  },
  {
    code: 'legend',
    name: 'Leyenda',
    description: 'Contribuye durante 90 días consecutivos.',
    unlockLine: 'Noventa días de contribución. Eso es leyenda.',
    icon: '🔥',
    category: 'constancia',
    rarity: 'legendary',
    xpReward: 500,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 210,
    rule: { type: 'consecutive_days', target: 90 },
    triggers: ['STREAK_DAY_COMPLETED'],
    progressNoun: 'días consecutivos',
  },
  {
    code: 'first_mark',
    name: 'Primera huella',
    description: 'Una oferta alcanza 10 votos.',
    unlockLine: 'Una de tus ofertas ya dejó huella.',
    icon: '📈',
    category: 'impacto',
    rarity: 'common',
    xpReward: 50,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 220,
    rule: { type: 'single_offer_votes', target: 10 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos en tu mejor oferta',
  },
  {
    code: 'growing_impact',
    name: 'Impacto creciente',
    description: 'Una oferta alcanza 50 votos.',
    unlockLine: 'Una oferta tuya está moviendo a la comunidad.',
    icon: '📈',
    category: 'impacto',
    rarity: 'uncommon',
    xpReward: 100,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 230,
    rule: { type: 'single_offer_votes', target: 50 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos en tu mejor oferta',
  },
  {
    code: 'featured_offer',
    name: 'Oferta destacada',
    description: 'Una oferta alcanza 100 votos.',
    unlockLine: 'Una oferta tuya se volvió referencia.',
    icon: '📈',
    category: 'impacto',
    rarity: 'rare',
    xpReward: 200,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 240,
    rule: { type: 'single_offer_votes', target: 100 },
    triggers: ['OFFER_RECEIVED_VOTE', 'OFFER_FEATURED'],
    progressNoun: 'votos en tu mejor oferta',
  },
  {
    code: 'influential_hunter',
    name: 'Cazador influyente',
    description: 'Tus ofertas acumulan 500 votos.',
    unlockLine: 'El conjunto de tu cacería ya pesa.',
    icon: '📈',
    category: 'impacto',
    rarity: 'epic',
    xpReward: 250,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 250,
    rule: { type: 'received_votes', target: 500 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos acumulados',
  },
  {
    code: 'great_impact',
    name: 'Gran impacto',
    description: 'Tus ofertas acumulan 2,500 votos.',
    unlockLine: 'Miles de apoyos salieron de tus hallazgos.',
    icon: '📈',
    category: 'impacto',
    rarity: 'legendary',
    xpReward: 400,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 260,
    rule: { type: 'received_votes', target: 2500 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos acumulados',
  },
  {
    code: 'aventa_footprint',
    name: 'Huella Aventa',
    description: 'Tus ofertas acumulan 10,000 votos.',
    unlockLine: 'Dejaste una huella difícil de igualar.',
    icon: '👑',
    category: 'impacto',
    rarity: 'mythic',
    xpReward: 500,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 270,
    rule: { type: 'received_votes', target: 10000 },
    triggers: ['OFFER_RECEIVED_VOTE'],
    progressNoun: 'votos acumulados',
  },
  {
    code: 'first_step',
    name: 'Primer paso',
    description: 'Alcanza Nivel 2.',
    unlockLine: 'Diste el primer paso de nivel en Aventa.',
    icon: '🧠',
    category: 'experiencia',
    rarity: 'common',
    xpReward: 0,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 280,
    rule: { type: 'level', target: 2 },
    triggers: ['LEVEL_REACHED'],
    progressNoun: 'nivel',
  },
  {
    code: 'contributor',
    name: 'Contribuidor',
    description: 'Alcanza Nivel 3.',
    unlockLine: 'Tu nivel ya habla de contribución.',
    icon: '🧠',
    category: 'experiencia',
    rarity: 'uncommon',
    xpReward: 0,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 290,
    rule: { type: 'level', target: 3 },
    triggers: ['LEVEL_REACHED'],
    progressNoun: 'nivel',
  },
  {
    code: 'hunter_rank',
    name: 'Cazador',
    description: 'Alcanza Nivel 4, el máximo de reputación.',
    unlockLine: 'El nivel de cazador es prestigio, no otro puñado de XP.',
    icon: '🧠',
    category: 'experiencia',
    rarity: 'rare',
    xpReward: 0,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 300,
    rule: { type: 'level', target: 4 },
    triggers: ['LEVEL_REACHED'],
    progressNoun: 'nivel',
  },
  {
    code: 'explorer',
    name: 'Explorador',
    description: 'Alcanza Nivel 10.',
    unlockLine: 'Explorador es un reconocimiento, no una fuente de XP.',
    icon: '🧠',
    category: 'experiencia',
    rarity: 'epic',
    xpReward: 0,
    isHidden: false,
    reveal: 'visible',
    /** La reputación termina en nivel 4; se reactiva solo si existe un nivel 10. */
    isActive: false,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 310,
    rule: { type: 'level', target: 10 },
    triggers: ['LEVEL_REACHED'],
    progressNoun: 'nivel',
  },
  {
    code: 'early_bird',
    name: 'Madrugador',
    description: 'Publica una oferta excepcional durante la ventana de la mañana.',
    unlockLine: 'Encontraste una ganga antes de que despertara el feed.',
    icon: '💎',
    category: 'especiales',
    rarity: 'rare',
    xpReward: 75,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 320,
    rule: { type: 'dawn' },
    triggers: ['OFFER_APPROVED', 'QUALITY_THRESHOLD_REACHED'],
    progressNoun: 'oferta excepcional de mañana',
  },
  {
    code: 'night_hunter',
    name: 'Cazador nocturno',
    description: 'Encuentra una oferta excepcional durante la noche.',
    unlockLine: 'La noche también tuvo una ganga tuya.',
    icon: '💎',
    category: 'especiales',
    rarity: 'rare',
    xpReward: 75,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 330,
    rule: { type: 'night' },
    triggers: ['OFFER_APPROVED', 'QUALITY_THRESHOLD_REACHED'],
    progressNoun: 'oferta excepcional de noche',
  },
  {
    code: 'flash_hunter',
    name: 'Flash Hunter',
    description: 'Encuentra una oferta excepcional con una ventana de disponibilidad muy corta.',
    unlockLine: 'Cazaste algo que casi no alcanzó a durar.',
    icon: '⚡',
    category: 'especiales',
    rarity: 'epic',
    xpReward: 100,
    isHidden: false,
    reveal: 'visible',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 340,
    rule: { type: 'flash' },
    triggers: ['OFFER_APPROVED', 'QUALITY_THRESHOLD_REACHED'],
    progressNoun: 'oferta relámpago',
  },
  {
    code: 'black_friday_hunter',
    name: 'Black Friday Hunter',
    description: 'Publica una oferta excepcional durante Black Friday.',
    unlockLine: 'Llegaste con una ganga en la ventana de Black Friday.',
    icon: '🛒',
    category: 'especiales',
    rarity: 'legendary',
    xpReward: 150,
    isHidden: true,
    reveal: 'during_window',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 350,
    rule: { type: 'black_friday' },
    triggers: ['OFFER_APPROVED', 'QUALITY_THRESHOLD_REACHED'],
    progressNoun: 'oferta de Black Friday',
  },
  {
    code: 'season_hunter',
    name: 'Cazador de temporada',
    description: 'Publica una oferta excepcional durante una temporada de Aventa.',
    unlockLine: 'La temporada tuvo un hallazgo tuyo que sí valía.',
    icon: '🎄',
    category: 'especiales',
    rarity: 'epic',
    xpReward: 100,
    isHidden: true,
    reveal: 'during_window',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: false,
    displayOrder: 360,
    rule: { type: 'season' },
    triggers: ['OFFER_APPROVED', 'QUALITY_THRESHOLD_REACHED'],
    progressNoun: 'oferta de temporada',
  },
  {
    code: 'secret_offer',
    name: 'Oferta secreta',
    description: 'Encuentra una oferta excepcional, de las que casi no aparecen.',
    unlockLine: 'Esto casi no pasa. Y te pasó a ti.',
    icon: '🥷',
    category: 'especiales',
    rarity: 'mythic',
    xpReward: 250,
    isHidden: true,
    reveal: 'until_unlocked',
    isActive: true,
    isRepeatable: false,
    v1Spotlight: true,
    displayOrder: 370,
    rule: { type: 'secret' },
    triggers: ['OFFER_APPROVED', 'QUALITY_THRESHOLD_REACHED'],
    progressNoun: 'oferta secreta',
  },
];

const byCode = new Map(ACHIEVEMENT_CATALOG.map((item) => [item.code, item]));

export function achievementByCode(code: string): AchievementDefinition | null {
  return byCode.get(code) ?? null;
}

export function activeAchievements(): AchievementDefinition[] {
  return ACHIEVEMENT_CATALOG.filter((item) => item.isActive);
}
