/**
 * Cuando og:site_name falta o es genérico, infiere nombre de tienda conocida por el host.
 * Orden: más específico primero (subdominios / TLD regional).
 */
const SUFFIX_TO_STORE: Array<{ suffix: string; store: string }> = [
  { suffix: 'mercadolibre.com.mx', store: 'Mercado Libre' },
  { suffix: 'mercadolibre.com', store: 'Mercado Libre' },
  { suffix: 'amazon.com.mx', store: 'Amazon' },
  { suffix: 'amazon.com', store: 'Amazon' },
  { suffix: 'walmart.com.mx', store: 'Walmart' },
  { suffix: 'walmart.com', store: 'Walmart' },
  { suffix: 'walmart.page.link', store: 'Walmart' },
  { suffix: 'liverpool.com.mx', store: 'Liverpool' },
  { suffix: 'liverpool.app.link', store: 'Liverpool' },
  { suffix: 'liverpool.com', store: 'Liverpool' },
  { suffix: 'shein.com.mx', store: 'SHEIN' },
  { suffix: 'shein.com', store: 'SHEIN' },
  { suffix: 'temu.com', store: 'Temu' },
  { suffix: 'temu.to', store: 'Temu' },
  { suffix: 'aliexpress.com', store: 'AliExpress' },
  { suffix: 'aliexpress.us', store: 'AliExpress' },
  { suffix: 'ebay.com.mx', store: 'eBay' },
  { suffix: 'ebay.mx', store: 'eBay' },
  { suffix: 'ebay.com', store: 'eBay' },
  { suffix: 'ebay.to', store: 'eBay' },
  { suffix: 'ebay.us', store: 'eBay' },
  { suffix: 'bodegaaurrera.com.mx', store: 'Bodega Aurrera' },
  { suffix: 'sams.com.mx', store: "Sam's Club" },
  { suffix: 'costco.com.mx', store: 'Costco' },
  { suffix: 'cost.co', store: 'Costco' },
  { suffix: 'chedraui.com.mx', store: 'Chedraui' },
  { suffix: 'soriana.com', store: 'Soriana' },
  { suffix: 'cityclub.com.mx', store: 'City Club' },
  { suffix: 'heb.com.mx', store: 'H-E-B' },
  { suffix: 'lacomer.com.mx', store: 'La Comer' },
  { suffix: 'citymarket.com.mx', store: 'City Market' },
  { suffix: 'fresko.com.mx', store: 'Fresko' },
  { suffix: 'superama.com.mx', store: 'Superama' },
  { suffix: 'superama.com', store: 'Superama' },
  { suffix: 'elektra.com.mx', store: 'Elektra' },
  { suffix: 'elektra.mx', store: 'Elektra' },
  { suffix: 'coppel.com.mx', store: 'Coppel' },
  { suffix: 'coppel.com', store: 'Coppel' },
  { suffix: 'coppel.app.link', store: 'Coppel' },
  { suffix: 'elpalaciodehierro.com', store: 'El Palacio de Hierro' },
  { suffix: 'sears.com.mx', store: 'Sears' },
  { suffix: 'suburbia.com.mx', store: 'Suburbia' },
  { suffix: 'sanborns.com.mx', store: 'Sanborns' },
  { suffix: 'officedepot.com.mx', store: 'Office Depot' },
  { suffix: 'officemax.com.mx', store: 'OfficeMax' },
  { suffix: 'homedepot.com.mx', store: 'Home Depot' },
  { suffix: 'sodimac.com.mx', store: 'Sodimac' },
  { suffix: 'cyberpuerta.com.mx', store: 'Cyberpuerta' },
  { suffix: 'cyberpuerta.com', store: 'Cyberpuerta' },
  { suffix: 'cyberpuerta.mx', store: 'Cyberpuerta' },
  { suffix: 'ddtech.mx', store: 'DDTech' },
  { suffix: 'pcel.com', store: 'PCEL' },
  { suffix: 'doto.com.mx', store: 'Doto' },
  { suffix: 'steren.com.mx', store: 'Steren' },
  { suffix: 'radioshack.com.mx', store: 'RadioShack' },
  { suffix: 'claroshop.com.mx', store: 'ClaroShop' },
  { suffix: 'claroshop.com', store: 'ClaroShop' },
  { suffix: 'ishopmixup.com', store: 'iShop Mixup' },
  { suffix: 'mixup.com.mx', store: 'Mixup' },
  { suffix: 'apple.com.mx', store: 'Apple' },
  { suffix: 'apple.com', store: 'Apple' },
  { suffix: 'nike.com', store: 'Nike' },
  { suffix: 'adidas.mx', store: 'adidas' },
  { suffix: 'adidas.com', store: 'adidas' },
  { suffix: 'innovasport.com', store: 'Innova Sport' },
  { suffix: 'priceshoes.com', store: 'Price Shoes' },
  { suffix: 'andrea.com.mx', store: 'Andrea' },
  { suffix: 'shopee.com.mx', store: 'Shopee' },
  { suffix: 'shopee.mx', store: 'Shopee' },
  { suffix: 'shp.ee', store: 'Shopee' },
  { suffix: 'linio.com.mx', store: 'Linio' },
];

export function inferStoreFromHostname(hostname: string): string | null {
  const h = hostname.replace(/^www\./, '').toLowerCase();
  if (!h) return null;
  for (const { suffix, store } of SUFFIX_TO_STORE) {
    if (h === suffix || h.endsWith(`.${suffix}`)) return store;
  }
  return null;
}
