import { CHEDRAUI_DISCOVERY_SURFACES, CHEDRAUI_OBSERVED_SURFACES } from '@/lib/hunter/dayToDay/surfaces';
import type { RetailerDiscoveryProfile, RetailerDiscoveryId, RetailerSurfaceSpec } from './types';

function chedrauiSurfaces(): RetailerSurfaceSpec[] {
  return [...CHEDRAUI_DISCOVERY_SURFACES, ...CHEDRAUI_OBSERVED_SURFACES].map((s) => ({
    id: s.id,
    url: s.url,
    kind: s.kind,
    status: s.status,
    notes: s.notes,
    locPattern: s.locPattern,
    maxPages: s.maxPages,
  }));
}

export const RETAILER_DISCOVERY_PROFILES: RetailerDiscoveryProfile[] = [
  {
    retailer: 'bodega_aurrera_mx',
    displayName: 'Bodega Aurrera',
    country: 'MX',
    origin: 'https://www.bodegaaurrera.com.mx',
    robotsUrl: 'https://www.bodegaaurrera.com.mx/robots.txt',
    publicSurfaces: [
      {
        id: 'content_ofertas',
        url: 'https://www.bodegaaurrera.com.mx/content/ofertas',
        kind: 'item_list',
        status: 'DEGRADED',
        notes: 'FASE 9: robots-ok, HTTP 200, ItemList vacío (SPA). Cero evidencia.',
        maxPages: 1,
      },
      {
        id: 'ofertas',
        url: 'https://www.bodegaaurrera.com.mx/ofertas',
        kind: 'item_list',
        status: 'DEGRADED',
        notes: 'FASE 9: HTTP 404. No es superficie usable.',
        maxPages: 1,
      },
    ],
    robotsStatus: 'allow_limited',
    termsStatus: 'ok',
    discoveryMethods: ['public_page', 'sitemap'],
    promotionSurfaces: ['content_ofertas', 'ofertas'],
    productSurfaces: ['productSitemap'],
    evidenceTypes: ['none'],
    antiBotRisk: 'high',
    expectedYield: 'low',
    complianceStatus: 'DEGRADED',
    implementationStatus: 'DEGRADED',
    recommendation: 'No activar. /content/ofertas es SPA vacía; /ofertas 404. Sin yield.',
    complexity: 'high',
    expectedSupplyFrequency: 'low',
  },
  {
    retailer: 'walmart_mx',
    displayName: 'Walmart México',
    country: 'MX',
    origin: 'https://www.walmart.com.mx',
    robotsUrl: 'https://www.walmart.com.mx/robots.txt',
    publicSurfaces: [
      {
        id: 'content_ofertas',
        url: 'https://www.walmart.com.mx/content/ofertas',
        kind: 'item_list',
        status: 'DEGRADED',
        notes: 'FASE 9: robots-ok, HTTP 200, ItemList vacío. PDPs históricos con challenge. Sin bypass.',
        maxPages: 1,
      },
      {
        id: 'ofertas',
        url: 'https://www.walmart.com.mx/ofertas',
        kind: 'item_list',
        status: 'DEGRADED',
        notes: 'FASE 9: HTTP 404. No es superficie usable.',
        maxPages: 1,
      },
    ],
    robotsStatus: 'allow_limited',
    termsStatus: 'ok',
    discoveryMethods: ['public_page', 'sitemap'],
    promotionSurfaces: ['content_ofertas', 'ofertas'],
    productSurfaces: ['productSitemap'],
    evidenceTypes: ['none'],
    antiBotRisk: 'high',
    expectedYield: 'none',
    complianceStatus: 'DEGRADED',
    implementationStatus: 'DEGRADED',
    recommendation: 'No activar. Listings sin evidencia. No convertir Walmart en incidente operativo.',
    complexity: 'high',
    expectedSupplyFrequency: 'none',
  },
  {
    retailer: 'home_depot_mx',
    displayName: 'Home Depot',
    country: 'MX',
    origin: 'https://www.homedepot.com.mx',
    robotsUrl: 'https://www.homedepot.com.mx/robots.txt',
    publicSurfaces: [
      {
        id: 'ofertas',
        url: 'https://www.homedepot.com.mx/ofertas',
        kind: 'item_list',
        status: 'NOT_CONFIGURED',
        notes: 'FASE 9: robots-ok, HTTP 200, sin Crawl-delay, ItemList JSON-LD vacío. Sin adapter.',
        maxPages: 1,
      },
      {
        id: 'promociones',
        url: 'https://www.homedepot.com.mx/promociones',
        kind: 'item_list',
        status: 'NOT_CONFIGURED',
        notes: 'FASE 9: robots-ok, HTTP 200, sin productos estructurados. No heredar % de landing.',
        maxPages: 1,
      },
    ],
    robotsStatus: 'allow_broad',
    termsStatus: 'review',
    discoveryMethods: ['public_page', 'sitemap'],
    promotionSurfaces: ['ofertas', 'promociones'],
    productSurfaces: ['sitemap_10351', 'pdp'],
    evidenceTypes: ['current_price'],
    antiBotRisk: 'low',
    expectedYield: 'none',
    complianceStatus: 'CATALOG_ONLY',
    implementationStatus: 'NOT_CONFIGURED',
    recommendation:
      'FASE 9.1: sitemap→PDP funciona y es catálogo. Sin originalPrice ni promo product-bound. Slugs 2x1 del sitemap son stale (canonical/título sin 2x1). No hay sitemap de promociones. No adapter. No activar.',
    complexity: 'medium',
    expectedSupplyFrequency: 'unknown',
  },
  {
    retailer: 'chedraui_mx',
    displayName: 'Chedraui',
    country: 'MX',
    origin: 'https://www.chedraui.com.mx',
    robotsUrl: 'https://www.chedraui.com.mx/robots.txt',
    publicSurfaces: chedrauiSurfaces(),
    robotsStatus: 'restrictive',
    termsStatus: 'ok',
    discoveryMethods: ['item_list', 'sitemap', 'seed_pdp'],
    promotionSurfaces: ['promociones_nuestras_marcas', 'promociones_perecederos', 'sitemap_promo_slug'],
    productSurfaces: ['pdp_jsonld'],
    evidenceTypes: ['current_price', 'promotion'],
    antiBotRisk: 'low',
    expectedYield: 'low',
    complianceStatus: 'CATALOG_ONLY',
    implementationStatus: 'CATALOG_ONLY',
    recommendation:
      'No activar. Listings CATALOG_ONLY. Type B funciona en PDP, sin canal sostenible. Sitemap slug yield 0.',
    complexity: 'medium',
    expectedSupplyFrequency: 'low',
  },
  {
    retailer: 'liverpool_mx',
    displayName: 'Liverpool',
    country: 'MX',
    origin: 'https://www.liverpool.com.mx',
    robotsUrl: 'https://www.liverpool.com.mx/robots.txt',
    publicSurfaces: [],
    robotsStatus: 'allow_broad',
    termsStatus: 'review',
    discoveryMethods: [],
    promotionSurfaces: [],
    productSurfaces: [],
    evidenceTypes: ['none'],
    antiBotRisk: 'medium',
    expectedYield: 'unknown',
    complianceStatus: 'NOT_CONFIGURED',
    implementationStatus: 'NOT_CONFIGURED',
    recommendation: 'Fuera de FASE 9. No investigar en este ciclo.',
    complexity: 'medium',
    expectedSupplyFrequency: 'unknown',
  },
  {
    retailer: 'soriana_mx',
    displayName: 'Soriana',
    country: 'MX',
    origin: 'https://www.soriana.com',
    robotsUrl: 'https://www.soriana.com/robots.txt',
    publicSurfaces: [],
    robotsStatus: 'unknown',
    termsStatus: 'blocked',
    discoveryMethods: [],
    promotionSurfaces: [],
    productSurfaces: [],
    evidenceTypes: ['none'],
    antiBotRisk: 'high',
    expectedYield: 'none',
    complianceStatus: 'BLOCKED_PENDING_POLICY_REVIEW',
    implementationStatus: 'BLOCKED_PENDING_POLICY_REVIEW',
    recommendation: 'Bloqueada. Términos restringen spiders/robots. No implementar.',
    complexity: 'high',
    expectedSupplyFrequency: 'none',
  },
];

export function profileFor(id: RetailerDiscoveryId): RetailerDiscoveryProfile | undefined {
  return RETAILER_DISCOVERY_PROFILES.find((p) => p.retailer === id);
}

export function profilesForInvestigation(): RetailerDiscoveryProfile[] {
  return RETAILER_DISCOVERY_PROFILES.filter((p) =>
    p.retailer === 'bodega_aurrera_mx' ||
    p.retailer === 'walmart_mx' ||
    p.retailer === 'home_depot_mx',
  );
}
