import type { HealthAreaId, TeamId } from '@/app/admin/owner/command/types';

/**
 * Explicación humana de cada módulo del Founder OS.
 * El estado, lo que requiere atención y la última actualización NO se escriben aquí:
 * se derivan en vivo de las mismas señales que usa el Control Center.
 */
export type FounderModule = {
  href: string;
  name: string;
  /** Mínimo 10 líneas, en lenguaje de negocio. */
  whatIs: string[];
  whyExists: string;
  protects: string;
  measures: string;
  howToRead: string;
  owner: string;
  /** Área de salud del Control Center que resume este módulo; null si es informativo. */
  healthArea: HealthAreaId | null;
  /** Equipos cuyas prioridades se muestran como «qué requiere atención». */
  teams: TeamId[];
  /** Solo visible tras «Ver detalles técnicos». */
  technical: string[];
  /** Las subrutas son pestañas del mismo módulo (no herramientas distintas). */
  includesSubpages?: boolean;
};

export const FOUNDER_MODULES: FounderModule[] = [
  {
    href: '/admin/moderation',
    name: 'Moderación',
    whatIs: [
      'Es la puerta por la que pasa cada oferta antes de que la vea la comunidad.',
      'Aquí llegan las ofertas que suben los cazadores y las que propone el bot.',
      'Cada oferta se revisa: precio real, tienda confiable, foto y enlace correctos.',
      'Quien modera decide aprobar, pedir cambios o rechazar con un motivo claro.',
      'Las ofertas aprobadas pasan al feed; las rechazadas no se publican.',
      'También llegan aquí los reportes de la comunidad sobre ofertas ya publicadas.',
      'Un reporte puede terminar en corrección, expiración o retiro de la oferta.',
      'La cola muestra primero lo más urgente y lo de mayor valor para la comunidad.',
      'Una cola sana significa que las buenas ofertas llegan rápido al feed.',
      'Una cola acumulada significa ofertas que caducan antes de publicarse.',
    ],
    whyExists: 'Para que el feed solo tenga ofertas verdaderas: es la promesa central de Aventa.',
    protects: 'La confianza de la comunidad y la reputación de Aventa frente a tiendas y usuarios.',
    measures: 'Ofertas pendientes, tiempo de espera, aprobadas y rechazadas, reportes abiertos.',
    howToRead: 'Pocas pendientes y espera corta es lo ideal. Si la espera crece, falta capacidad de moderación.',
    owner: 'Equipo de Moderación',
    healthArea: 'CATALOG',
    teams: ['moderacion', 'comunidad'],
    technical: ['Ruta: /admin/moderation (+ /approved, /rejected, /reports).', 'Datos: /api/admin/owner-dashboard (moderación) y cola de moderación.'],
    includesSubpages: true,
  },
  {
    href: '/admin/hunter',
    name: 'Supply · Hunter',
    whatIs: [
      'Es el motor que busca ofertas por su cuenta en las tiendas conectadas.',
      'Revisa fuentes como Mercado Libre, Amazon y otras tiendas de forma periódica.',
      'Cuando detecta un precio que parece oferta, lo propone como candidato.',
      'El motor observa y propone: no publica ni rechaza nada por sí solo.',
      'Cada candidato pasa a Moderación, donde una persona decide.',
      'Aquí ves si el bot está encendido, pausado o apagado.',
      'También ves qué fuentes responden bien y cuáles están fallando.',
      'Si una fuente falla, esa tienda deja de alimentar el catálogo.',
      'Un bot sano mantiene el feed con ofertas nuevas todos los días.',
      'Un bot detenido deja el catálogo dependiendo solo de los cazadores.',
    ],
    whyExists: 'Para que el feed tenga ofertas frescas aunque la comunidad todavía sea pequeña.',
    protects: 'La frescura del catálogo y la constancia de ofertas nuevas.',
    measures: 'Estado del bot, fuentes activas, candidatos encontrados y listos para revisión.',
    howToRead: 'Bot encendido y fuentes en verde es lo esperado. Fuentes en rojo piden revisión técnica.',
    owner: 'Equipo Hunter',
    healthArea: 'HUNTER',
    teams: ['hunter'],
    technical: ['Ruta: /admin/hunter.', 'El motor corre en modo observación; la publicación siempre requiere moderación.'],
  },
  {
    href: '/admin/users',
    name: 'Usuarios',
    whatIs: [
      'Es el directorio de las personas registradas en Aventa.',
      'Muestra quién se registró, cuándo entró por última vez y su estado.',
      'Sirve para encontrar a un usuario concreto cuando hay un caso que atender.',
      'Desde aquí se puede ver si una cuenta está suspendida y por qué.',
      'Las suspensiones existen para frenar spam, fraude o abuso.',
      'No es una herramienta de marketing: es una herramienta de cuidado.',
      'Para entender el historial de un caso, revisa también Actividad.',
      'Úsalo con criterio: una suspensión afecta la experiencia de una persona real.',
      'Una comunidad sana tiene pocas suspensiones y muchos usuarios activos.',
      'Muchas suspensiones seguidas suelen indicar un ataque o un problema de reglas.',
    ],
    whyExists: 'Para atender casos concretos de personas y proteger a la comunidad de abusos.',
    protects: 'La seguridad de la comunidad y el trato justo a cada usuario.',
    measures: 'Usuarios registrados, actividad reciente y cuentas suspendidas.',
    howToRead: 'Crecimiento constante y pocas suspensiones es lo sano. Picos de suspensiones merecen revisión.',
    owner: 'Equipo de Comunidad',
    healthArea: 'COMMUNITY',
    teams: ['comunidad'],
    technical: ['Ruta: /admin/users.', 'Historial: /admin/logs.'],
  },
  {
    href: '/admin/owner/crecimiento',
    name: 'Crecimiento',
    whatIs: [
      'Es la guía de qué hacer ahora para que Aventa crezca de forma sana.',
      'Reúne lo que conviene atender antes de atraer más usuarios.',
      'Incluye una lista de preparación: infraestructura y operación listas.',
      'Muestra costos e infraestructura para crecer sin sorpresas.',
      'Propone una hoja de ruta para escalar sin rehacer el producto.',
      'No es un tablero de métricas en vivo: para eso existe Métricas en vivo.',
      'Es un espacio para decidir prioridades de crecimiento.',
      'Conecta producto, operación y costos en una sola lectura.',
      'Un crecimiento sano llega cuando el producto aguanta la demanda.',
      'Crecer antes de estar listos suele romper la experiencia.',
    ],
    whyExists: 'Para crecer a propósito y no por accidente.',
    protects: 'La experiencia del usuario cuando llega más gente.',
    measures: 'Preparación para lanzamiento, costos e infraestructura, siguientes pasos.',
    howToRead: 'Si la lista de preparación tiene pendientes, todavía no conviene empujar tráfico.',
    owner: 'Equipo de Growth',
    healthArea: 'GROWTH',
    teams: ['growth'],
    technical: ['Ruta: /admin/owner/crecimiento.'],
  },
  {
    href: '/admin/metrics',
    name: 'Métricas en vivo',
    whatIs: [
      'Es la lectura numérica de cómo se está usando Aventa.',
      'Muestra usuarios activos y actividad sobre las ofertas.',
      'Permite comparar periodos para ver si algo sube o baja.',
      'Sirve para confirmar con datos lo que se intuye en el día a día.',
      'Las cifras se calculan con la actividad real registrada.',
      'Si una cifra no está disponible, se indica en lugar de inventarla.',
      'Es útil después de un cambio de producto o una campaña.',
      'También ayuda a detectar caídas antes de que se noten en la comunidad.',
      'Una tendencia estable o al alza es lo esperado.',
      'Una caída fuerte sin explicación merece revisar Salud del sistema.',
    ],
    whyExists: 'Para decidir con datos y no solo con intuición.',
    protects: 'La calidad de las decisiones de producto y crecimiento.',
    measures: 'Usuarios activos, interacción con ofertas y su evolución.',
    howToRead: 'Mira la tendencia, no un solo día. Compara contra el periodo anterior.',
    owner: 'Equipo de Growth',
    healthArea: 'GROWTH',
    teams: ['growth'],
    technical: ['Ruta: /admin/metrics.'],
  },
  {
    href: '/admin/commissions',
    name: 'Afiliación y comisiones',
    whatIs: [
      'Es donde se registra el dinero que las tiendas pagan a Aventa por comisión.',
      'Cuando Amazon o Mercado Libre pagan, el monto se registra aquí.',
      'Si esa venta vino del enlace de un cazador, le corresponde una parte.',
      'El resto de la comisión se queda en Aventa.',
      'Nada se paga automáticamente: cada paso requiere confirmación.',
      'Los pagos están protegidos por controles que impiden mover dinero por error.',
      'Si algo no cuadra, el sistema bloquea antes de pagar.',
      'Aquí se ve qué está confirmado y qué solo es estimado.',
      'Un estimado no es dinero cobrado: solo el confirmado cuenta como ingreso.',
      'Esta sección se revisa con calma; nunca con prisa.',
    ],
    whyExists: 'Para que el dinero de Aventa y de los cazadores sea trazable y justo.',
    protects: 'El dinero de Aventa, el de los cazadores y la confianza en el programa.',
    measures: 'Comisiones registradas, parte de cazadores, confirmado frente a estimado.',
    howToRead: 'Solo el ingreso confirmado es real. Si aparece un bloqueo, es una protección, no un fallo.',
    owner: 'Equipo de Finanzas',
    healthArea: 'MONETIZATION',
    teams: ['finanzas'],
    technical: ['Ruta: /admin/commissions.', 'Los controles de dinero están congelados por diseño; esta vista no los modifica.'],
  },
  {
    href: '/admin/rewards',
    name: 'Recompensas',
    whatIs: [
      'Es el programa que reconoce a los cazadores por aportar buenas ofertas.',
      'Muestra lo que cada cazador ha generado y lo que tiene pendiente.',
      'Las recompensas dependen de ingresos confirmados, no de estimados.',
      'Nada se paga sin revisión: cada pago pasa por aprobación.',
      'Existen protecciones para revertir recompensas si una venta se cancela.',
      'Aquí se ve el saldo pendiente con cada cazador.',
      'Ese saldo es una obligación de Aventa con su comunidad.',
      'Mantenerlo claro evita malentendidos con los cazadores.',
      'Un programa sano paga a tiempo lo que corresponde.',
      'Un saldo que crece sin pagos merece revisión con Finanzas.',
    ],
    whyExists: 'Para que cazar en Aventa valga la pena y la comunidad crezca.',
    protects: 'La relación con los cazadores y el dinero comprometido con ellos.',
    measures: 'Saldo pendiente, recompensas generadas, pagos aprobados.',
    howToRead: 'Pendiente bajo y pagos al día es lo sano. Un pendiente alto es deuda con la comunidad.',
    owner: 'Equipo de Finanzas',
    healthArea: 'MONETIZATION',
    teams: ['finanzas'],
    technical: ['Ruta: /admin/rewards.', 'Pagos sujetos al congelamiento del flujo de dinero.'],
  },
  {
    href: '/admin/health',
    name: 'Salud del sistema',
    whatIs: [
      'Es el chequeo médico de la plataforma.',
      'Revisa que los servicios y las tareas automáticas respondan.',
      'Cada revisión aparece en verde, amarillo o rojo.',
      'Verde significa que funciona como se espera.',
      'Amarillo significa que funciona, pero algo conviene revisar.',
      'Rojo significa que algo dejó de funcionar y afecta al producto.',
      'Aquí se detectan problemas antes de que los note la comunidad.',
      'No hace falta entender cada revisión: basta con mirar el color.',
      'Si algo está en rojo, se avisa al equipo de Producto.',
      'Los detalles técnicos quedan disponibles para quien los resuelve.',
    ],
    whyExists: 'Para saber en segundos si Aventa está funcionando bien.',
    protects: 'La disponibilidad del producto para toda la comunidad.',
    measures: 'Estado de servicios, tareas automáticas e integridad de datos.',
    howToRead: 'Todo en verde: no hay nada que hacer. Cualquier rojo: avisar a Producto.',
    owner: 'Equipo de Producto',
    healthArea: 'PRODUCT',
    teams: ['producto'],
    technical: ['Ruta: /admin/health.'],
  },
  {
    href: '/admin/operaciones',
    name: 'Centro de operaciones',
    whatIs: [
      'Es el mapa por áreas de cómo está funcionando Aventa.',
      'Muestra el pulso del producto y los semáforos de cada área.',
      'Incluye la decisión de Go/No-Go con sus razones.',
      'Permite copiar un reporte completo para compartirlo o revisarlo.',
      'Indica si hay ofertas de prueba visibles en la página principal.',
      'Reúne las revisiones de integridad en un solo lugar.',
      'Sirve para preparar decisiones importantes, como un lanzamiento.',
      'No reemplaza al Control Center: lo complementa con más detalle.',
      'Un centro en verde indica que la operación está en orden.',
      'Un semáforo en rojo indica qué área necesita atención primero.',
    ],
    whyExists: 'Para tener una visión operativa completa cuando hay que decidir algo grande.',
    protects: 'La calidad de las decisiones operativas y de lanzamiento.',
    measures: 'Semáforos por área, integridad, alertas y control de producto.',
    howToRead: 'Empieza por el Go/No-Go y luego revisa el área en rojo, si la hay.',
    owner: 'Equipo de Operaciones',
    healthArea: 'PRODUCT',
    teams: ['operaciones'],
    technical: ['Ruta: /admin/operaciones.'],
  },
  {
    href: '/admin/sistemas/mapa',
    name: 'Mapa de sistemas',
    whatIs: [
      'Es el plano de cómo está construido Aventa.',
      'Muestra las piezas del producto y cómo se conectan entre sí.',
      'Sirve para entender qué se afecta cuando algo cambia.',
      'Ayuda a explicar Aventa a alguien nuevo en el equipo.',
      'No mide nada en vivo: es un mapa de referencia.',
      'Cada pieza indica su propósito en palabras simples.',
      'Es útil antes de pedir un cambio grande.',
      'También ayuda a ubicar a quién preguntar por cada parte.',
      'Mantenerlo al día evita decisiones a ciegas.',
      'Si una pieza no aparece aquí, conviene documentarla.',
    ],
    whyExists: 'Para que el producto se pueda entender y delegar sin depender de una sola persona.',
    protects: 'El conocimiento del producto y la capacidad de delegar.',
    measures: 'No mide: describe.',
    howToRead: 'Úsalo como mapa: busca la pieza que te interesa y sigue sus conexiones.',
    owner: 'Owner',
    healthArea: null,
    teams: [],
    technical: ['Ruta: /admin/sistemas/mapa.'],
  },
  {
    href: '/admin/team',
    name: 'Roles y permisos',
    whatIs: [
      'Es donde se decide quién puede entrar a las herramientas internas de Aventa.',
      'Cada persona del staff tiene un rol: owner, administración, moderación o análisis.',
      'El rol define qué pantallas puede ver y qué acciones puede hacer.',
      'Dar un rol es dar acceso real: conviene hacerlo con cuidado.',
      'Quitar un rol corta el acceso de inmediato.',
      'Este espacio no organiza el trabajo diario: eso vive en Equipos de trabajo.',
      'Aquí se controla el acceso; en Equipos de trabajo se organiza la tarea.',
      'Mantener pocos roles amplios reduce riesgos.',
      'Cada persona debería tener el rol mínimo que necesita.',
      'Revisar esta lista de vez en cuando evita accesos olvidados.',
    ],
    whyExists: 'Para que solo las personas correctas accedan a herramientas sensibles.',
    protects: 'La seguridad de Aventa y de los datos de la comunidad.',
    measures: 'Personas con acceso y el rol de cada una.',
    howToRead: 'Si ves a alguien que ya no colabora, quítale el rol.',
    owner: 'Owner',
    healthArea: null,
    teams: [],
    technical: ['Ruta: /admin/team (roles globales del panel).'],
  },
  {
    href: '/admin/owner/team-management',
    name: 'Equipos de trabajo',
    whatIs: [
      'Es donde se organizan los equipos que trabajan en Aventa día a día.',
      'Cada equipo tiene miembros y un área de responsabilidad.',
      'Aquí se invita, activa o pausa a los miembros de cada equipo.',
      'Los miembros trabajan desde su propio espacio: Team OS.',
      'Como Owner supervisas su trabajo desde Team Hub, no desde Team OS.',
      'Esta separación es intencional: el Owner dirige, los equipos ejecutan.',
      'Cada equipo debería saber qué hacer, por qué y cuándo está terminado.',
      'Un equipo sin miembros activos es un área sin atender.',
      'Los cambios aquí no dan acceso al panel del Owner.',
      'El acceso a herramientas internas se controla en Roles y permisos.',
    ],
    whyExists: 'Para delegar el trabajo diario sin perder la visión de conjunto.',
    protects: 'La capacidad operativa de Aventa y la separación entre dirigir y ejecutar.',
    measures: 'Equipos, miembros activos y su estado.',
    howToRead: 'Cada área clave debería tener al menos un miembro activo.',
    owner: 'Owner',
    healthArea: null,
    teams: [],
    technical: ['Ruta: /admin/owner/team-management.', 'Supervisión del trabajo: /equipo (Team Hub).'],
  },
];

export function findFounderModule(pathname: string): FounderModule | null {
  return (
    FOUNDER_MODULES.find((m) => m.href === pathname || (m.includesSubpages && pathname.startsWith(`${m.href}/`))) ?? null
  );
}
