import type { HealthAreaId, TeamId } from '@/app/admin/owner/command/types';

/**
 * Explicación humana de cada módulo del Founder OS.
 * El estado, lo que requiere atención y la última actualización NO se escriben aquí:
 * se derivan en vivo de las mismas señales que usa el Control Center.
 */
export type FounderModule = {
  href: string;
  name: string;
  /** Mínimo 10 líneas, en lenguaje de negocio. */
  whatIs: string[];
  whyExists: string;
  protects: string;
  measures: string;
  howToRead: string;
  /** Qué decisión permite tomar. */
  decides: string;
  /** Qué NO controla (para no buscarlo aquí). */
  doesNotControl: string;
  /** Cuándo conviene entrar. */
  whenToEnter: string;
  owner: string;
  /** Área de salud del Control Center que resume este módulo; null si es informativo. */
  healthArea: HealthAreaId | null;
  /** Equipos cuyas prioridades se muestran como «qué requiere atención». */
  teams: TeamId[];
  /** Solo visible tras «Ver detalles técnicos». */
  technical: string[];
  /** Las subrutas son pestañas del mismo módulo (no herramientas distintas). */
  includesSubpages?: boolean;
};

export const FOUNDER_MODULES: FounderModule[] = [
  {
    href: '/admin/moderation',
    name: 'Moderation',
    whatIs: [
      'Es la puerta por la que pasa cada oferta antes de que la vea la comunidad.',
      'Aquí llegan las ofertas que suben los cazadores y las que propone el bot.',
      'Cada oferta se revisa: precio real, tienda confiable, foto y enlace correctos.',
      'Quien modera decide aprobar, pedir cambios o rechazar con un motivo claro.',
      'Las ofertas aprobadas pasan al feed; las rechazadas no se publican.',
      'También llegan aquí los reportes de la comunidad sobre ofertas ya publicadas.',
      'Un reporte puede terminar en corrección, expiración o retiro de la oferta.',
      'La cola muestra primero lo más urgente y lo de mayor valor para la comunidad.',
      'Una cola sana significa que las buenas ofertas llegan rápido al feed.',
      'Una cola acumulada significa ofertas que caducan antes de publicarse.',
    ],
    whyExists: 'Para que el feed solo tenga ofertas verdaderas: es la promesa central de Aventa.',
    protects: 'La confianza de la comunidad y la reputación de Aventa frente a tiendas y usuarios.',
    measures: 'Ofertas pendientes, tiempo de espera, aprobadas y rechazadas, reportes abiertos.',
    howToRead: 'Pocas pendientes y espera corta es lo ideal. Si la espera crece, falta capacidad de moderación.',
    decides: 'Qué entra al feed hoy y si hace falta más gente moderando.',
    doesNotControl: 'No cambia precios en tiendas ni decide pagos a cazadores.',
    whenToEnter: 'Cada día, y siempre que la cola o los reportes crezcan.',
    owner: 'Equipo de Moderación',
    healthArea: 'CATALOG',
    teams: ['moderacion', 'comunidad'],
    technical: ['Ruta: /admin/moderation (+ /approved, /rejected, /reports).', 'Datos: /api/admin/owner-dashboard (moderación) y cola de moderación.'],
    includesSubpages: true,
  },
  {
    href: '/admin/hunter',
    name: 'Supply',
    whatIs: [
      'Es el motor que busca ofertas por su cuenta en las tiendas conectadas.',
      'Revisa fuentes como Mercado Libre, Amazon y otras tiendas de forma periódica.',
      'Cuando detecta un precio que parece oferta, lo propone como candidato.',
      'El motor observa y propone: no publica ni rechaza nada por sí solo.',
      'Cada candidato pasa a Moderación, donde una persona decide.',
      'Aquí ves si el bot está encendido, pausado o apagado.',
      'También ves qué fuentes responden bien y cuáles están fallando.',
      'Si una fuente falla, esa tienda deja de alimentar el catálogo.',
      'Un bot sano mantiene el feed con ofertas nuevas todos los días.',
      'Un bot detenido deja el catálogo dependiendo solo de los cazadores.',
    ],
    whyExists: 'Para que el feed tenga ofertas frescas aunque la comunidad todavía sea pequeña.',
    protects: 'La frescura del catálogo y la constancia de ofertas nuevas.',
    measures: 'Estado del bot, fuentes activas, candidatos encontrados y listos para revisión.',
    howToRead: 'Bot encendido y fuentes en verde es lo esperado. Fuentes en rojo piden revisión técnica.',
    decides: 'Si el bot debe seguir corriendo, pausarse o revisar una fuente que falla.',
    doesNotControl: 'No publica ofertas: todo pasa por Moderation.',
    whenToEnter: 'Cuando bajan las ofertas nuevas o una fuente aparece en rojo.',
    owner: 'Equipo Hunter',
    healthArea: 'HUNTER',
    teams: ['hunter'],
    technical: ['Ruta: /admin/hunter.', 'El motor corre en modo observación; la publicación siempre requiere moderación.'],
  },
  {
    href: '/admin/users',
    name: 'Users',
    whatIs: [
      'Es el directorio de las personas registradas en Aventa.',
      'Muestra quién se registró, cuándo entró por última vez y su estado.',
      'Sirve para encontrar a un usuario concreto cuando hay un caso que atender.',
      'Desde aquí se puede ver si una cuenta está suspendida y por qué.',
      'Las suspensiones existen para frenar spam, fraude o abuso.',
      'No es una herramienta de marketing: es una herramienta de cuidado.',
      'Para entender el historial de un caso, revisa también Actividad.',
      'Úsalo con criterio: una suspensión afecta la experiencia de una persona real.',
      'Una comunidad sana tiene pocas suspensiones y muchos usuarios activos.',
      'Muchas suspensiones seguidas suelen indicar un ataque o un problema de reglas.',
    ],
    whyExists: 'Para atender casos concretos de personas y proteger a la comunidad de abusos.',
    protects: 'La seguridad de la comunidad y el trato justo a cada usuario.',
    measures: 'Usuarios registrados, actividad reciente y cuentas suspendidas.',
    howToRead: 'Crecimiento constante y pocas suspensiones es lo sano. Picos de suspensiones merecen revisión.',
    decides: 'Si una cuenta concreta necesita atención o una suspensión.',
    doesNotControl: 'No da acceso al panel: eso vive en Roles y permisos.',
    whenToEnter: 'Cuando hay un caso concreto de un usuario o un pico de abusos.',
    owner: 'Equipo de Comunidad',
    healthArea: 'COMMUNITY',
    teams: ['comunidad'],
    technical: ['Ruta: /admin/users.', 'Historial: /admin/logs.'],
  },
  {
    href: '/admin/owner/crecimiento',
    name: 'Growth',
    whatIs: [
      'Es la guía de qué hacer ahora para que Aventa crezca de forma sana.',
      'Reúne lo que conviene atender antes de atraer más usuarios.',
      'Incluye una lista de preparación: infraestructura y operación listas.',
      'Muestra costos e infraestructura para crecer sin sorpresas.',
      'Propone una hoja de ruta para escalar sin rehacer el producto.',
      'No es un tablero de métricas en vivo: para eso existe Métricas en vivo.',
      'Es un espacio para decidir prioridades de crecimiento.',
      'Conecta producto, operación y costos en una sola lectura.',
      'Un crecimiento sano llega cuando el producto aguanta la demanda.',
      'Crecer antes de estar listos suele romper la experiencia.',
    ],
    whyExists: 'Para crecer a propósito y no por accidente.',
    protects: 'La experiencia del usuario cuando llega más gente.',
    measures: 'Preparación para lanzamiento, costos e infraestructura, siguientes pasos.',
    howToRead: 'Si la lista de preparación tiene pendientes, todavía no conviene empujar tráfico.',
    decides: 'Si conviene empujar tráfico o primero preparar el producto.',
    doesNotControl: 'No mide en vivo: para eso existe Live Metrics.',
    whenToEnter: 'Antes de una campaña o de una decisión de crecimiento.',
    owner: 'Equipo de Growth',
    healthArea: 'GROWTH',
    teams: ['growth'],
    technical: ['Ruta: /admin/owner/crecimiento.'],
  },
  {
    href: '/admin/metrics',
    name: 'Live Metrics',
    whatIs: [
      'Es la lectura numérica de cómo se está usando Aventa.',
      'Muestra usuarios activos y actividad sobre las ofertas.',
      'Permite comparar periodos para ver si algo sube o baja.',
      'Sirve para confirmar con datos lo que se intuye en el día a día.',
      'Las cifras se calculan con la actividad real registrada.',
      'Si una cifra no está disponible, se indica en lugar de inventarla.',
      'Es útil después de un cambio de producto o una campaña.',
      'También ayuda a detectar caídas antes de que se noten en la comunidad.',
      'Una tendencia estable o al alza es lo esperado.',
      'Una caída fuerte sin explicación merece revisar Salud del sistema.',
    ],
    whyExists: 'Para decidir con datos y no solo con intuición.',
    protects: 'La calidad de las decisiones de producto y crecimiento.',
    measures: 'Usuarios activos, interacción con ofertas y su evolución.',
    howToRead: 'Mira la tendencia, no un solo día. Compara contra el periodo anterior.',
    decides: 'Si un cambio o una campaña funcionó, con datos.',
    doesNotControl: 'No modifica nada del producto: solo lee.',
    whenToEnter: 'Después de un cambio, una campaña o si sospechas una caída.',
    owner: 'Equipo de Growth',
    healthArea: 'GROWTH',
    teams: ['growth'],
    technical: ['Ruta: /admin/metrics.'],
  },
  {
    href: '/admin/commissions',
    name: 'Money',
    whatIs: [
      'Es donde se registra el dinero que las tiendas pagan a Aventa por comisión.',
      'Cuando Amazon o Mercado Libre pagan, el monto se registra aquí.',
      'Si esa venta vino del enlace de un cazador, le corresponde una parte.',
      'El resto de la comisión se queda en Aventa.',
      'Nada se paga automáticamente: cada paso requiere confirmación.',
      'Los pagos están protegidos por controles que impiden mover dinero por error.',
      'Si algo no cuadra, el sistema bloquea antes de pagar.',
      'Aquí se ve qué está confirmado y qué solo es estimado.',
      'Un estimado no es dinero cobrado: solo el confirmado cuenta como ingreso.',
      'Esta sección se revisa con calma; nunca con prisa.',
    ],
    whyExists: 'Para que el dinero de Aventa y de los cazadores sea trazable y justo.',
    protects: 'El dinero de Aventa, el de los cazadores y la confianza en el programa.',
    measures: 'Comisiones registradas, parte de cazadores, confirmado frente a estimado.',
    howToRead: 'Solo el ingreso confirmado es real. Si aparece un bloqueo, es una protección, no un fallo.',
    decides: 'Qué comisiones registrar y qué parte corresponde a cada cazador.',
    doesNotControl: 'No paga por sí solo: los pagos siguen congelados por seguridad.',
    whenToEnter: 'Cuando llega un pago de una tienda o hay que revisar números del mes.',
    owner: 'Equipo de Finanzas',
    healthArea: 'MONETIZATION',
    teams: ['finanzas'],
    technical: ['Ruta: /admin/commissions.', 'Los controles de dinero están congelados por diseño; esta vista no los modifica.'],
  },
  {
    href: '/admin/rewards',
    name: 'Rewards Ops',
    whatIs: [
      'Es el programa que reconoce a los cazadores por aportar buenas ofertas.',
      'Muestra lo que cada cazador ha generado y lo que tiene pendiente.',
      'Las recompensas dependen de ingresos confirmados, no de estimados.',
      'Nada se paga sin revisión: cada pago pasa por aprobación.',
      'Existen protecciones para revertir recompensas si una venta se cancela.',
      'Aquí se ve el saldo pendiente con cada cazador.',
      'Ese saldo es una obligación de Aventa con su comunidad.',
      'Mantenerlo claro evita malentendidos con los cazadores.',
      'Un programa sano paga a tiempo lo que corresponde.',
      'Un saldo que crece sin pagos merece revisión con Finanzas.',
    ],
    whyExists: 'Para que cazar en Aventa valga la pena y la comunidad crezca.',
    protects: 'La relación con los cazadores y el dinero comprometido con ellos.',
    measures: 'Saldo pendiente, recompensas generadas, pagos aprobados.',
    howToRead: 'Pendiente bajo y pagos al día es lo sano. Un pendiente alto es deuda con la comunidad.',
    decides: 'Qué recompensas revisar y cuánto se debe a la comunidad.',
    doesNotControl: 'No activa pagos: el flujo de dinero sigue congelado.',
    whenToEnter: 'Al revisar el saldo con cazadores o preparar un pago futuro.',
    owner: 'Equipo de Finanzas',
    healthArea: 'MONETIZATION',
    teams: ['finanzas'],
    technical: ['Ruta: /admin/rewards.', 'Pagos sujetos al congelamiento del flujo de dinero.'],
  },
  {
    href: '/admin/health',
    name: 'Health',
    whatIs: [
      'Es el chequeo médico de la plataforma.',
      'Revisa que los servicios y las tareas automáticas respondan.',
      'Cada revisión aparece en verde, amarillo o rojo.',
      'Verde significa que funciona como se espera.',
      'Amarillo significa que funciona, pero algo conviene revisar.',
      'Rojo significa que algo dejó de funcionar y afecta al producto.',
      'Aquí se detectan problemas antes de que los note la comunidad.',
      'No hace falta entender cada revisión: basta con mirar el color.',
      'Si algo está en rojo, se avisa al equipo de Producto.',
      'Los detalles técnicos quedan disponibles para quien los resuelve.',
    ],
    whyExists: 'Para saber en segundos si Aventa está funcionando bien.',
    protects: 'La disponibilidad del producto para toda la comunidad.',
    measures: 'Estado de servicios, tareas automáticas e integridad de datos.',
    howToRead: 'Todo en verde: no hay nada que hacer. Cualquier rojo: avisar a Producto.',
    decides: 'Si hay que avisar a Producto porque algo dejó de funcionar.',
    doesNotControl: 'No arregla nada por sí solo: diagnostica.',
    whenToEnter: 'Si algo se ve raro en el producto o una métrica cae sin motivo.',
    owner: 'Equipo de Producto',
    healthArea: 'PRODUCT',
    teams: ['producto'],
    technical: ['Ruta: /admin/health.'],
  },
  {
    href: '/admin/operaciones',
    name: 'Operaciones',
    whatIs: [
      'Es el mapa por áreas de cómo está funcionando Aventa.',
      'Muestra el pulso del producto y los semáforos de cada área.',
      'Incluye la decisión de Go/No-Go con sus razones.',
      'Permite copiar un reporte completo para compartirlo o revisarlo.',
      'Indica si hay ofertas de prueba visibles en la página principal.',
      'Reúne las revisiones de integridad en un solo lugar.',
      'Sirve para preparar decisiones importantes, como un lanzamiento.',
      'No reemplaza al Control Center: lo complementa con más detalle.',
      'Un centro en verde indica que la operación está en orden.',
      'Un semáforo en rojo indica qué área necesita atención primero.',
    ],
    whyExists: 'Para tener una visión operativa completa cuando hay que decidir algo grande.',
    protects: 'La calidad de las decisiones operativas y de lanzamiento.',
    measures: 'Semáforos por área, integridad, alertas y control de producto.',
    howToRead: 'Empieza por el Go/No-Go y luego revisa el área en rojo, si la hay.',
    decides: 'Go/No-Go de un lanzamiento y qué área atender primero.',
    doesNotControl: 'No reemplaza al Control Center ni cambia datos de ofertas.',
    whenToEnter: 'Antes de un lanzamiento o de una decisión operativa grande.',
    owner: 'Equipo de Operaciones',
    healthArea: 'PRODUCT',
    teams: ['operaciones'],
    technical: ['Ruta: /admin/operaciones.'],
  },
  {
    href: '/admin/sistemas/mapa',
    name: 'Systems Map',
    whatIs: [
      'Es el plano de cómo está construido Aventa.',
      'Muestra las piezas del producto y cómo se conectan entre sí.',
      'Sirve para entender qué se afecta cuando algo cambia.',
      'Ayuda a explicar Aventa a alguien nuevo en el equipo.',
      'No mide nada en vivo: es un mapa de referencia.',
      'Cada pieza indica su propósito en palabras simples.',
      'Es útil antes de pedir un cambio grande.',
      'También ayuda a ubicar a quién preguntar por cada parte.',
      'Mantenerlo al día evita decisiones a ciegas.',
      'Si una pieza no aparece aquí, conviene documentarla.',
    ],
    whyExists: 'Para que el producto se pueda entender y delegar sin depender de una sola persona.',
    protects: 'El conocimiento del producto y la capacidad de delegar.',
    measures: 'No mide: describe.',
    howToRead: 'Úsalo como mapa: busca la pieza que te interesa y sigue sus conexiones.',
    decides: 'A quién involucrar y qué se afecta antes de pedir un cambio.',
    doesNotControl: 'No mide ni modifica nada: es un mapa.',
    whenToEnter: 'Antes de pedir un cambio grande o al explicar Aventa a alguien nuevo.',
    owner: 'Owner',
    healthArea: null,
    teams: [],
    technical: ['Ruta: /admin/sistemas/mapa.'],
  },
  {
    href: '/admin/team',
    name: 'Roles y permisos',
    whatIs: [
      'Es donde se decide quién puede entrar a las herramientas internas de Aventa.',
      'Cada persona del staff tiene un rol: owner, administración, moderación o análisis.',
      'El rol define qué pantallas puede ver y qué acciones puede hacer.',
      'Dar un rol es dar acceso real: conviene hacerlo con cuidado.',
      'Quitar un rol corta el acceso de inmediato.',
      'Este espacio no organiza el trabajo diario: eso vive en Equipos de trabajo.',
      'Aquí se controla el acceso; en Equipos de trabajo se organiza la tarea.',
      'Mantener pocos roles amplios reduce riesgos.',
      'Cada persona debería tener el rol mínimo que necesita.',
      'Revisar esta lista de vez en cuando evita accesos olvidados.',
    ],
    whyExists: 'Para que solo las personas correctas accedan a herramientas sensibles.',
    protects: 'La seguridad de Aventa y de los datos de la comunidad.',
    measures: 'Personas con acceso y el rol de cada una.',
    howToRead: 'Si ves a alguien que ya no colabora, quítale el rol.',
    decides: 'Quién del staff puede entrar a las herramientas internas.',
    doesNotControl: 'No organiza el trabajo diario: eso vive en Equipos de trabajo.',
    whenToEnter: 'Al sumar o despedir a alguien del staff, y en revisiones periódicas.',
    owner: 'Owner',
    healthArea: null,
    teams: [],
    technical: ['Ruta: /admin/team (roles globales del panel).'],
  },
  {
    href: '/admin/owner/team-management',
    name: 'Equipos de trabajo',
    whatIs: [
      'Es donde se organizan los equipos que trabajan en Aventa día a día.',
      'Cada equipo tiene miembros y un área de responsabilidad.',
      'Aquí se invita, activa o pausa a los miembros de cada equipo.',
      'Los miembros trabajan desde su propio espacio: Team OS.',
      'Como Owner supervisas su trabajo desde Team Hub, no desde Team OS.',
      'Esta separación es intencional: el Owner dirige, los equipos ejecutan.',
      'Cada equipo debería saber qué hacer, por qué y cuándo está terminado.',
      'Un equipo sin miembros activos es un área sin atender.',
      'Los cambios aquí no dan acceso al panel del Owner.',
      'El acceso a herramientas internas se controla en Roles y permisos.',
    ],
    whyExists: 'Para delegar el trabajo diario sin perder la visión de conjunto.',
    protects: 'La capacidad operativa de Aventa y la separación entre dirigir y ejecutar.',
    measures: 'Equipos, miembros activos y su estado.',
    howToRead: 'Cada área clave debería tener al menos un miembro activo.',
    decides: 'Quién trabaja en cada equipo y si un área queda sin atender.',
    doesNotControl: 'No da acceso al panel del Owner: eso vive en Roles y permisos.',
    whenToEnter: 'Al sumar a alguien a un equipo o si un área se queda sin gente.',
    owner: 'Owner',
    healthArea: null,
    teams: [],
    technical: ['Ruta: /admin/owner/team-management.', 'Supervisión del trabajo: /equipo (Team Hub).'],
  },
  {
    href: '/admin/operaciones/trabajo',
    name: 'Bot y trabajo',
    whatIs: [
      'Es el tablero de trabajo diario del Owner.',
      'Muestra si el bot buscador está encendido o pausado.',
      'Permite pausar el bot o pedirle una búsqueda ahora.',
      'Reúne los programas de afiliados con los que trabaja Aventa.',
      'Incluye una libreta del fundador: tareas, costos e ideas.',
      'Esa libreta se guarda solo en este navegador.',
      'Si cambias de equipo, la libreta no viaja contigo.',
      'No reemplaza a Supply: allí está la salud detallada del bot.',
      'Sirve para operar rápido sin entrar a varias pantallas.',
      'Úsalo como mesa de trabajo, no como fuente de verdad.',
    ],
    whyExists: 'Para operar el día a día del bot y del negocio desde un solo lugar.',
    protects: 'La continuidad del bot y el orden de las tareas del fundador.',
    measures: 'Estado del bot y pendientes anotados.',
    howToRead: 'Bot encendido y lista de tareas corta es lo esperado.',
    decides: 'Si pausar o correr el bot ahora.',
    doesNotControl: 'No publica ofertas ni mueve dinero.',
    whenToEnter: 'Al empezar el día o si el bot necesita una pausa.',
    owner: 'Owner',
    healthArea: 'HUNTER',
    teams: ['hunter'],
    technical: ['Ruta: /admin/operaciones/trabajo.', 'Libreta del fundador en almacenamiento local del navegador.'],
  },
  {
    href: '/admin/logs',
    name: 'Activity',
    whatIs: [
      'Es el historial de acciones administrativas en Aventa.',
      'Registra quién hizo qué y cuándo dentro del panel.',
      'Sirve para reconstruir un caso: una oferta rechazada, una cuenta suspendida.',
      'No es un tablero de métricas: es una bitácora.',
      'Cada entrada indica la acción y su autor.',
      'Ayuda a entender decisiones tomadas por el equipo.',
      'También ayuda a detectar errores o abusos internos.',
      'No se edita: es un registro para consultar.',
      'Revisarlo de vez en cuando da tranquilidad.',
      'Si algo cambió sin explicación, empieza por aquí.',
    ],
    whyExists: 'Para que cada acción del equipo sea trazable.',
    protects: 'La transparencia interna y la capacidad de auditar decisiones.',
    measures: 'Acciones administrativas recientes y sus autores.',
    howToRead: 'Busca la fecha o la persona y lee la secuencia de acciones.',
    decides: 'Si una acción del equipo necesita corrección o conversación.',
    doesNotControl: 'No deshace acciones: solo las muestra.',
    whenToEnter: 'Cuando algo cambió y quieres saber quién y cuándo.',
    owner: 'Owner',
    healthArea: null,
    teams: [],
    technical: ['Ruta: /admin/logs.'],
  },
  {
    href: '/admin/infraestructura',
    name: 'Infrastructure',
    whatIs: [
      'Es la lista de servicios externos de los que depende Aventa.',
      'Agrupa los servicios por función.',
      'Cada servicio muestra su estado actual.',
      'Sirve para saber de qué depende el producto para funcionar.',
      'Si un proveedor falla, aquí se ve cuál.',
      'Ayuda a planear costos y límites antes de crecer.',
      'No es un monitor segundo a segundo.',
      'Complementa a Health, que revisa el producto por dentro.',
      'Mantener este mapa claro evita sorpresas.',
      'Los respaldos de la base de datos se gestionan fuera de este panel.',
    ],
    whyExists: 'Para conocer y vigilar las dependencias externas de Aventa.',
    protects: 'La continuidad del servicio ante fallas de proveedores.',
    measures: 'Estado de cada servicio externo.',
    howToRead: 'Todo en verde: no hay nada que hacer. Un servicio en rojo: revisar al proveedor.',
    decides: 'Si un problema viene de un proveedor y a quién escalarlo.',
    doesNotControl: 'No cambia planes ni configura proveedores.',
    whenToEnter: 'Si Health marca un problema externo o antes de crecer.',
    owner: 'Equipo de Producto',
    healthArea: 'PRODUCT',
    teams: ['producto'],
    technical: ['Ruta: /admin/infraestructura.'],
  },
  {
    href: '/admin/contexto',
    name: 'Configuration',
    whatIs: [
      'Es el índice del panel explicado por áreas.',
      'Cada área describe para qué sirve y enlaza a sus herramientas.',
      'Sirve como manual rápido de Aventa para el Owner.',
      'También sirve para orientar a alguien nuevo en el equipo.',
      'No cambia la configuración del producto por sí mismo.',
      'Enlaza a las herramientas donde sí se hacen los cambios.',
      'Es útil cuando no recuerdas dónde vive algo.',
      'Complementa al Systems Map, que muestra cómo se conecta todo.',
      'Mantenerlo al día ahorra preguntas repetidas.',
      'Si una herramienta no aparece aquí, conviene documentarla.',
    ],
    whyExists: 'Para encontrar cualquier herramienta sin memorizar nombres internos.',
    protects: 'El conocimiento del producto y la autonomía del Owner.',
    measures: 'No mide: orienta.',
    howToRead: 'Busca el área que te interesa y sigue su enlace.',
    decides: 'A qué herramienta ir para resolver algo.',
    doesNotControl: 'No modifica ajustes del producto.',
    whenToEnter: 'Cuando no sabes dónde está algo.',
    owner: 'Owner',
    healthArea: null,
    teams: [],
    technical: ['Ruta: /admin/contexto.'],
  },
  {
    href: '/admin/technical',
    name: 'Technical',
    whatIs: [
      'Es la vista técnica en bruto del bot y de la integridad de datos.',
      'Muestra el estado detallado del bot buscador.',
      'Muestra el resultado de las revisiones de integridad.',
      'Permite copiar un reporte completo para revisarlo con calma.',
      'Está pensada para quien resuelve problemas técnicos.',
      'No hace falta entenderla para operar Aventa.',
      'Para una lectura de negocio, usa Supply y Health.',
      'No cambia nada: solo muestra y copia.',
      'Es útil cuando algo falla y hay que explicarlo a soporte.',
      'Los términos técnicos viven aquí para no ensuciar el resto del panel.',
    ],
    whyExists: 'Para diagnosticar problemas técnicos con todo el detalle disponible.',
    protects: 'La rapidez para resolver incidentes.',
    measures: 'Estado del bot e integridad de datos, en detalle.',
    howToRead: 'Si no hay errores visibles, no hay nada que hacer.',
    decides: 'Si un incidente necesita escalarse a soporte técnico.',
    doesNotControl: 'No ejecuta correcciones.',
    whenToEnter: 'Cuando Supply o Health marcan un problema y se necesita el detalle.',
    owner: 'Equipo de Producto',
    healthArea: 'PRODUCT',
    teams: ['producto'],
    technical: ['Ruta: /admin/technical.'],
  },
  {
    href: '/admin/machine-clients',
    name: 'Clientes MCP',
    whatIs: [
      'Es donde se dan de alta los bots externos que proponen ofertas, como Grok.',
      'Un bot externo solo sugiere candidatos: no publica, no modera y no gana dinero.',
      'Cada candidato entra a la cola de lotes y una persona del equipo decide.',
      'Cada cliente tiene un nombre, permisos, un autor bot y una cuota diaria.',
      'El token se muestra una sola vez al crearlo y Aventa no lo puede recuperar.',
      'Pausar detiene sus envíos. Reanudar los vuelve a permitir.',
      'Revocar es permanente: el cliente queda registrado y su token deja de servir.',
      'Para cambiar un token se crea un cliente nuevo y se revoca el anterior.',
      'La recepción general se enciende aparte, solo después de validarla en staging.',
      'El autor bot nunca es un Aventa Hunter ni una persona del equipo.',
    ],
    whyExists: 'Para recibir candidatos de bots externos sin abrir otra puerta de escritura.',
    protects: 'La moderación humana, el escritor único de ofertas y el dinero de los usuarios.',
    measures: 'Qué clientes existen, en qué estado están y cuánto pueden enviar al día.',
    howToRead: 'Activo envía. Pausado solo consulta. Revocado ya no entra.',
    decides: 'Qué bot puede proponer candidatos y con qué permisos.',
    doesNotControl: 'No publica ofertas, no modera y no toca recompensas ni pagos.',
    whenToEnter: 'Cuando vas a conectar, pausar o retirar un bot externo.',
    owner: 'Owner',
    healthArea: null,
    teams: ['producto'],
    technical: ['Tablas machine_clients y machine_client_calls. Endpoint MCP en /api/mcp. Kill switch MCP_INGEST_ENABLED.'],
  },
];

export function findFounderModule(pathname: string): FounderModule | null {
  return (
    FOUNDER_MODULES.find((m) => m.href === pathname || (m.includesSubpages && pathname.startsWith(`${m.href}/`))) ?? null
  );
}
